tinymce.addI18n("bg",{
"#":"#",
"Accessibility":"Достъпност",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Действие",
"Activity":"Дейност",
"Address":"Адрес",
"Advanced":"Разширени",
"Align":"Подравняване",
"Align center":"Центриране",
"Align left":"Подравняване вляво",
"Align right":"Подравняване вдясно",
"Alignment":"Подравняване",
"Alignment {0}":"",
"All":"Всички",
"Alternative description":"Алтернативно описание",
"Alternative source":"Алтернативен източник",
"Alternative source URL":"URL на алтернативен източник",
"Anchor":"Котва",
"Anchor...":"Котва...",
"Anchors":"Котви",
"Animals and Nature":"Животни и природа",
"Arrows":"Стрелки",
"B":"B",
"Background color":"Цвят на фона",
"Background color {0}":"",
"Black":"Черен",
"Block":"Блок",
"Block {0}":"",
"Blockquote":"Цитат",
"Blocks":"Блокове",
"Blue":"Син",
"Blue component":"Син компонент",
"Body":"Тяло",
"Bold":"Удебелен",
"Border":"Граница",
"Border color":"Цвят на границата",
"Border style":"Стил на границата",
"Border width":"Ширина на границата",
"Bottom":"Отдолу",
"Browse files":"",
"Browse for an image":"Избор на изображение",
"Browse links":"",
"Bullet list":"Списък с водещи символи",
"Cancel":"Отказ",
"Caption":"Заглавие",
"Cell":"Клетка",
"Cell padding":"Вътрешен отстъп на клетката",
"Cell properties":"Свойства на клетката",
"Cell spacing":"Външен отстъп на клетката",
"Cell styles":"Стилове на клетката",
"Cell type":"Тип на клетката",
"Center":"Център",
"Characters":"Символи",
"Characters (no spaces)":"Символи (без интервали)",
"Circle":"Кръг",
"Class":"Клас",
"Clear formatting":"Изчисти форматирането",
"Close":"Затвори",
"Code":"Код",
"Code sample...":"Пример за код...",
"Code view":"Преглед на кода",
"Color Picker":"Избор на цвят",
"Color swatch":"Образец на цвят",
"Cols":"Колони",
"Column":"Колона",
"Column clipboard actions":"Действия с буфера за колона",
"Column group":"Група колони",
"Column header":"Заглавие на колона",
"Constrain proportions":"Ограничи пропорциите",
"Copy":"Копирай",
"Copy column":"Копирай колона",
"Copy row":"Копирай ред",
"Could not find the specified string.":"Не може да се намери посоченият низ.",
"Could not load emojis":"Не може да се заредят емоджита",
"Count":"Брой",
"Currency":"Валута",
"Current window":"Текущ прозорец",
"Custom color":"Потребителски цвят",
"Custom...":"Персонализиран...",
"Cut":"Изрежи",
"Cut column":"Изрежи колона",
"Cut row":"Изрежи ред",
"Dark Blue":"Тъмносин",
"Dark Gray":"Тъмносив",
"Dark Green":"Тъмнозелен",
"Dark Orange":"Тъмнооранжев",
"Dark Purple":"Тъмновиолетов",
"Dark Red":"Тъмночервен",
"Dark Turquoise":"Тъмнотюркоазен",
"Dark Yellow":"Тъмножълт",
"Dashed":"Пунктиран",
"Date/time":"Дата/време",
"Decrease indent":"Намали отстъпа",
"Default":"По подразбиране",
"Delete accordion":"",
"Delete column":"Изтрий колона",
"Delete row":"Изтрий ред",
"Delete table":"Изтрий таблица",
"Dimensions":"Размери",
"Disc":"Диск",
"Div":"Div",
"Document":"Документ",
"Dotted":"Точков",
"Double":"Двойна",
"Drop an image here":"Пуснете изображение тук",
"Dropped file type is not supported":"Типът на файла не се поддържа",
"Edit":"Редактирай",
"Embed":"Вграден",
"Emojis":"Емоджита",
"Emojis...":"Емоджита...",
"Error":"Грешка",
"Error: Form submit field collision.":"Грешка: Конфликт на полета за изпращане на форма.",
"Error: No form element found.":"Грешка: Не е намерен елемент на форма.",
"Extended Latin":"Разширена латиница",
"Failed to initialize plugin: {0}":"Неуспешна инициализация на приставка: {0}",
"Failed to load plugin url: {0}":"Неуспешно зареждане на URL на приставка: {0}",
"Failed to load plugin: {0} from url {1}":"Неуспешно зареждане на приставка: {0} от URL {1}",
"Failed to upload image: {0}":"Неуспешно качване на изображение: {0}",
"File":"Файл",
"Find":"Намери",
"Find (if searchreplace plugin activated)":"Намери (ако приставката searchreplace е активирана)",
"Find and Replace":"Намери и замени",
"Find and replace...":"Намери и замени...",
"Find in selection":"Търси в избраното",
"Find whole words only":"Намери само цели думи",
"Flags":"Флагове",
"Focus to contextual toolbar":"Фокус върху контекстната лента с инструменти",
"Focus to element path":"Фокус върху пътя на елемента",
"Focus to menubar":"Фокус върху лентата с менюта",
"Focus to toolbar":"Фокус върху лентата с инструменти",
"Font":"Шрифт",
"Font size {0}":"",
"Font sizes":"Размери на шрифта",
"Font {0}":"",
"Fonts":"Шрифтове",
"Food and Drink":"Храна и напитки",
"Footer":"Долен колонтитул",
"Format":"Формат",
"Format {0}":"",
"Formats":"Формати",
"Fullscreen":"Пълен екран",
"G":"G",
"General":"Общи",
"Gray":"Сив",
"Green":"Зелен",
"Green component":"Зелен компонент",
"Groove":"Канал",
"Handy Shortcuts":"Полезни клавишни комбинации",
"Header":"Горен колонтитул",
"Header cell":"Клетка на горен колонтитул",
"Heading 1":"Заглавие 1",
"Heading 2":"Заглавие 2",
"Heading 3":"Заглавие 3",
"Heading 4":"Заглавие 4",
"Heading 5":"Заглавие 5",
"Heading 6":"Заглавие 6",
"Headings":"Заглавия",
"Height":"Височина",
"Help":"Помощ",
"Hex color code":"HEX код на цвят",
"Hidden":"Скрит",
"Horizontal align":"Хоризонтално подравняване",
"Horizontal line":"Хоризонтална линия",
"Horizontal space":"Хоризонтален интервал",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID трябва да започва с буква, последвана само от букви, цифри, тирета, точки, двоеточия или долни черти.",
"Image is decorative":"Изображението е декоративно",
"Image list":"Списък с изображения",
"Image title":"Заглавие на изображението",
"Image...":"Изображение...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP грешка на ImageProxy: Не може да се намери Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP грешка на ImageProxy: Неправилен URL на Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP грешка на ImageProxy: Отхвърлена заявка",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP грешка на ImageProxy: Неизвестна грешка на ImageProxy",
"Increase indent":"Увеличи отстъпа",
"Inline":"Вграден",
"Insert":"Вмъкни",
"Insert Template":"Вмъкни шаблон",
"Insert accordion":"",
"Insert column after":"Вмъкни колона отдясно",
"Insert column before":"Вмъкни колона отляво",
"Insert date/time":"Вмъкни дата/време",
"Insert image":"Вмъкни изображение",
"Insert link (if link plugin activated)":"Вмъкни връзка (ако приставката link е активирана)",
"Insert row after":"Вмъкни ред отдолу",
"Insert row before":"Вмъкни ред отгоре",
"Insert table":"Вмъкни таблица",
"Insert template...":"Вмъкни шаблон...",
"Insert video":"Вмъкни видео",
"Insert/Edit code sample":"Добави/Редактирай пример за код",
"Insert/edit image":"Вмъкни/редактирай изображение",
"Insert/edit link":"Вмъкни/редактирай връзка",
"Insert/edit media":"Вмъкни/редактирай мултимедия",
"Insert/edit video":"Вмъкни/редактирай видео",
"Inset":"Вложка",
"Invalid hex color code: {0}":"Невалиден HEX код на цвят: {0}",
"Invalid input":"Невалиден вход",
"Italic":"Курсив",
"Justify":"Подравняване по ширина",
"Keyboard Navigation":"Навигация с клавиатура",
"Language":"Език",
"Learn more...":"Научи повече...",
"Left":"Ляво",
"Left to right":"Отляво надясно",
"Light Blue":"Светлосин",
"Light Gray":"Светлосив",
"Light Green":"Светлозелен",
"Light Purple":"Светловиолетов",
"Light Red":"Светлочервен",
"Light Yellow":"Светложълт",
"Line height":"Височина на реда",
"Link list":"Списък с връзки",
"Link...":"Връзка...",
"List Properties":"Свойства на списъка",
"List properties...":"Свойства на списъка...",
"Loading emojis...":"Зареждане на емоджита...",
"Loading...":"Зареждане...",
"Lower Alpha":"Малки латински",
"Lower Greek":"Малки гръцки",
"Lower Roman":"Малки римски",
"Match case":"Съответствие на регистъра",
"Mathematical":"Математически",
"Media poster (Image URL)":"Постер на мултимедия (URL на изображение)",
"Media...":"Мултимедия...",
"Medium Blue":"Средносин",
"Medium Gray":"Средносив",
"Medium Purple":"Средновиолетов",
"Merge cells":"Обедини клетки",
"Middle":"Среда",
"Midnight Blue":"Полунощносин",
"More...":"Повече...",
"Name":"Име",
"Navy Blue":"Тъмносин",
"New document":"Нов документ",
"New window":"Нов прозорец",
"Next":"Следващ",
"No":"Не",
"No alignment":"Без подравняване",
"No color":"Без цвят",
"Nonbreaking space":"Неразделящ интервал",
"None":"Нито един",
"Numbered list":"Номериран списък",
"OR":"ИЛИ",
"Objects":"Обекти",
"Ok":"OK",
"Open help dialog":"Отвори диалог за помощ",
"Open link":"Отвори връзка",
"Open link in...":"Отвори връзка в...",
"Open popup menu for split buttons":"Отвори изскачащо меню за разделени бутони",
"Orange":"Оранжев",
"Outset":"Изрезка",
"Page break":"Разделител на страница",
"Paragraph":"Параграф",
"Paste":"Постави",
"Paste as text":"Постави като текст",
"Paste column after":"Постави колона отдясно",
"Paste column before":"Постави колона отляво",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Поставянето сега е в режим на обикновен текст. Съдържанието ще се поставя като обикновен текст, докато не изключите тази опция.",
"Paste or type a link":"Въведете или поставете връзка",
"Paste row after":"Постави ред отдолу",
"Paste row before":"Постави ред отгоре",
"Paste your embed code below:":"Поставете вградения код по-долу:",
"People":"Хора",
"Plugins":"Приставки",
"Plugins installed ({0}):":"Инсталирани приставки ({0}):",
"Powered by {0}":"Задвижвано от {0}",
"Pre":"Pre",
"Preferences":"Предпочитания",
"Preformatted":"Предварително форматиран",
"Premium plugins:":"Премиум приставки:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Преглед",
"Previous":"Предишен",
"Print":"Печат",
"Print...":"Печат...",
"Purple":"Виолетов",
"Quotations":"Цитати",
"R":"R",
"Range 0 to 255":"Диапазон от 0 до 255",
"Red":"Червен",
"Red component":"Червен компонент",
"Redo":"Повтори",
"Remove":"Премахни",
"Remove color":"Премахни цвят",
"Remove link":"Премахни връзка",
"Replace":"Замени",
"Replace all":"Замени всички",
"Replace with":"Замени с",
"Resize":"Промени размера",
"Restore last draft":"Възстанови последния чернова",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Област за форматиран текст",
"Rich Text Area. Press ALT-0 for help.":"Област за форматиран текст. Натиснете ALT-0 за помощ.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Област за форматиран текст. Натиснете ALT-F9 за меню, ALT-F10 за лента с инструменти, ALT-0 за помощ",
"Ridge":"Гребен",
"Right":"Дясно",
"Right to left":"Отдясно наляво",
"Row":"Ред",
"Row clipboard actions":"Действия с буфера за ред",
"Row group":"Група редове",
"Row header":"Заглавие на ред",
"Row properties":"Свойства на реда",
"Row type":"Тип на реда",
"Rows":"Редове",
"Save":"Запази",
"Save (if save plugin activated)":"Запази (ако приставката save е активирана)",
"Scope":"Обхват",
"Search":"Търсене",
"Select all":"Избери всички",
"Select...":"Избери...",
"Selection":"Избор",
"Shortcut":"Клавишна комбинация",
"Show blocks":"Покажи блокове",
"Show caption":"Покажи заглавие",
"Show invisible characters":"Покажи невидими символи",
"Size":"Размер",
"Solid":"Плътен",
"Source":"Източник",
"Source code":"Изходен код",
"Special Character":"Специален символ",
"Special character...":"Специален символ...",
"Split cell":"Раздели клетка",
"Square":"Квадрат",
"Start list at number":"Започни номерацията от",
"Strikethrough":"Зачертаване",
"Style":"Стил",
"Subscript":"Долен индекс",
"Superscript":"Горен индекс",
"Switch to or from fullscreen mode":"Превключи в или излез от режим на пълен екран",
"Symbols":"Символи",
"System Font":"Системен шрифт",
"Table":"Таблица",
"Table caption":"Заглавие на таблицата",
"Table properties":"Свойства на таблицата",
"Table styles":"Стилове на таблицата",
"Template":"Шаблон",
"Templates":"Шаблони",
"Text":"Текст",
"Text color":"Цвят на текста",
"Text color {0}":"",
"Text to display":"Текст за показване",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"Въведеният URL изглежда като имейл адрес. Искате ли да добавите необходимия префикс mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"Въведеният URL изглежда като външна връзка. Искате ли да добавите необходимия префикс http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"Въведеният URL изглежда като външна връзка. Искате ли да добавите необходимия префикс https://?",
"Title":"Заглавие",
"To open the popup, press Shift+Enter":"За да отворите изскачащото меню, натиснете Shift+Enter",
"Toggle accordion":"",
"Tools":"Инструменти",
"Top":"Отгоре",
"Travel and Places":"Пътувания и места",
"Turquoise":"Тюркоазен",
"Underline":"Подчертаване",
"Undo":"Отмени",
"Upload":"Качи",
"Uploading image":"Качване на изображение",
"Upper Alpha":"Големи латински",
"Upper Roman":"Големи римски",
"Url":"URL",
"User Defined":"Дефинирани от потребителя",
"Valid":"Валиден",
"Version":"Версия",
"Vertical align":"Вертикално подравняване",
"Vertical space":"Вертикален интервал",
"View":"Изглед",
"Visual aids":"Визуални подсказки",
"Warn":"Предупреждение",
"White":"Бял",
"Width":"Ширина",
"Word count":"Брой думи",
"Words":"Думи",
"Words: {0}":"Думи: {0}",
"Yellow":"Жълт",
"Yes":"Да",
"You are using {0}":"Използвате {0}",
"You have unsaved changes are you sure you want to navigate away?":"Имате незапазени промени. Сигурни ли сте, че искате да напуснете?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Вашият браузър не поддържа директен достъп до буфера за обмен. Моля, използвайте клавишните комбинации Ctrl+X/C/V.",
"alignment":"подравняване",
"austral sign":"символ на австрал",
"cedi sign":"символ на седи",
"colon sign":"двоеточие",
"cruzeiro sign":"символ на крузейро",
"currency sign":"символ на валута",
"dollar sign":"символ на долар",
"dong sign":"символ на донг",
"drachma sign":"символ на драхма",
"euro-currency sign":"символ на евро",
"example":"пример",
"formatting":"форматиране",
"french franc sign":"символ на френски франк",
"german penny symbol":"символ на германски пфениг",
"guarani sign":"символ на гуарани",
"history":"история",
"hryvnia sign":"символ на гривна",
"indentation":"отстъп",
"indian rupee sign":"символ на индийска рупия",
"kip sign":"символ на кип",
"lira sign":"символ на лира",
"livre tournois sign":"символ на ливър",
"manat sign":"символ на манат",
"mill sign":"символ на мил",
"naira sign":"символ на найра",
"new sheqel sign":"символ на нов шекел",
"nordic mark sign":"символ на нордическа марка",
"peseta sign":"символ на песета",
"peso sign":"символ на песо",
"ruble sign":"символ на рубла",
"rupee sign":"символ на рупия",
"spesmilo sign":"символ на спесмило",
"styles":"стилове",
"tenge sign":"символ на тенге",
"tugrik sign":"символ на тугрик",
"turkish lira sign":"символ на турска лира",
"won sign":"символ на вон",
"yen character":"символ на йена",
"yen/yuan character variant one":"символ на йена/юан, вариант 1",
"yuan character":"символ на юан",
"yuan character, in hong kong and taiwan":"символ на юан, Хонг Конг и Тайван",
"{0} characters":"{0} символа",
"{0} columns, {1} rows":"",
"{0} words":"{0} думи"
});
