tinymce.addI18n("bs",{
"#":"#",
"Accessibility":"Pristupačnost",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Akcija",
"Activity":"Aktivnost",
"Address":"Adresa",
"Advanced":"Napredno",
"Align":"Poravnaj",
"Align center":"Centriraj",
"Align left":"Poravnaj lijevo",
"Align right":"Poravnaj desno",
"Alignment":"Poravnanje",
"Alignment {0}":"",
"All":"Sve",
"Alternative description":"Alternativni opis",
"Alternative source":"Alternativni izvor",
"Alternative source URL":"URL alternativnog izvora",
"Anchor":"Sidro",
"Anchor...":"Sidro...",
"Anchors":"Sidra",
"Animals and Nature":"Životinje i priroda",
"Arrows":"Strelice",
"B":"B",
"Background color":"Boja pozadine",
"Background color {0}":"",
"Black":"Crna",
"Block":"Blok",
"Block {0}":"",
"Blockquote":"Blok citat",
"Blocks":"Blokovi",
"Blue":"Plava",
"Blue component":"Plava komponenta",
"Body":"Tijelo",
"Bold":"Podebljano",
"Border":"Granica",
"Border color":"Boja granice",
"Border style":"Stil granice",
"Border width":"Širina granice",
"Bottom":"Dno",
"Browse files":"",
"Browse for an image":"Pretraži sliku",
"Browse links":"",
"Bullet list":"Lista sa tačkama",
"Cancel":"Otkaži",
"Caption":"Naslov",
"Cell":"Ćelija",
"Cell padding":"Unutrašnji razmak ćelije",
"Cell properties":"Svojstva ćelije",
"Cell spacing":"Vanjski razmak ćelije",
"Cell styles":"Stilovi ćelije",
"Cell type":"Tip ćelije",
"Center":"Centar",
"Characters":"Znakovi",
"Characters (no spaces)":"Znakovi (bez razmaka)",
"Circle":"Krug",
"Class":"Klasa",
"Clear formatting":"Očisti formatiranje",
"Close":"Zatvori",
"Code":"Kod",
"Code sample...":"Primjer koda...",
"Code view":"Pregled koda",
"Color Picker":"Birač boja",
"Color swatch":"Uzorak boje",
"Cols":"Kolone",
"Column":"Kolona",
"Column clipboard actions":"Akcije međuspremnika za kolonu",
"Column group":"Grupa kolona",
"Column header":"Zaglavlje kolone",
"Constrain proportions":"Ograniči proporcije",
"Copy":"Kopiraj",
"Copy column":"Kopiraj kolonu",
"Copy row":"Kopiraj red",
"Could not find the specified string.":"Nije moguće pronaći navedeni string.",
"Could not load emojis":"Nije moguće učitati emojije",
"Count":"Broj",
"Currency":"Valuta",
"Current window":"Trenutni prozor",
"Custom color":"Prilagođena boja",
"Custom...":"Prilagođeno...",
"Cut":"Izreži",
"Cut column":"Izreži kolonu",
"Cut row":"Izreži red",
"Dark Blue":"Tamno plava",
"Dark Gray":"Tamno siva",
"Dark Green":"Tamno zelena",
"Dark Orange":"Tamno narančasta",
"Dark Purple":"Tamno ljubičasta",
"Dark Red":"Tamno crvena",
"Dark Turquoise":"Tamno tirkizna",
"Dark Yellow":"Tamno žuta",
"Dashed":"Isprekidana",
"Date/time":"Datum/vrijeme",
"Decrease indent":"Smanji uvlačenje",
"Default":"Zadano",
"Delete accordion":"",
"Delete column":"Obriši kolonu",
"Delete row":"Obriši red",
"Delete table":"Obriši tabelu",
"Dimensions":"Dimenzije",
"Disc":"Disk",
"Div":"Div",
"Document":"Dokument",
"Dotted":"Točkasta",
"Double":"Dvostruka",
"Drop an image here":"Ovdje ispustite sliku",
"Dropped file type is not supported":"Tip datoteke nije podržan",
"Edit":"Uredi",
"Embed":"Ugrađeno",
"Emojis":"Emojiji",
"Emojis...":"Emojiji...",
"Error":"Greška",
"Error: Form submit field collision.":"Greška: Kolizija polja za slanje forme.",
"Error: No form element found.":"Greška: Nije pronađen element forme.",
"Extended Latin":"Proširena latinica",
"Failed to initialize plugin: {0}":"Neuspješna inicijalizacija plugina: {0}",
"Failed to load plugin url: {0}":"Neuspješno učitavanje URL plugina: {0}",
"Failed to load plugin: {0} from url {1}":"Neuspješno učitavanje plugina: {0} iz URL {1}",
"Failed to upload image: {0}":"Neuspješno učitavanje slike: {0}",
"File":"Datoteka",
"Find":"Pronađi",
"Find (if searchreplace plugin activated)":"Pronađi (ako je plugin searchreplace aktiviran)",
"Find and Replace":"Pronađi i zamijeni",
"Find and replace...":"Pronađi i zamijeni...",
"Find in selection":"Traži u odabiru",
"Find whole words only":"Pronađi samo cijele riječi",
"Flags":"Zastave",
"Focus to contextual toolbar":"Fokus na kontekstnu traku alata",
"Focus to element path":"Fokus na putanju elementa",
"Focus to menubar":"Fokus na traku menija",
"Focus to toolbar":"Fokus na traku alata",
"Font":"Font",
"Font size {0}":"",
"Font sizes":"Veličine fonta",
"Font {0}":"",
"Fonts":"Fontovi",
"Food and Drink":"Hrana i piće",
"Footer":"Podnožje",
"Format":"Format",
"Format {0}":"",
"Formats":"Formati",
"Fullscreen":"Puni ekran",
"G":"G",
"General":"Općenito",
"Gray":"Siva",
"Green":"Zelena",
"Green component":"Zelena komponenta",
"Groove":"Urez",
"Handy Shortcuts":"Korisni prečaci",
"Header":"Zaglavlje",
"Header cell":"Ćelija zaglavlja",
"Heading 1":"Naslov 1",
"Heading 2":"Naslov 2",
"Heading 3":"Naslov 3",
"Heading 4":"Naslov 4",
"Heading 5":"Naslov 5",
"Heading 6":"Naslov 6",
"Headings":"Naslovi",
"Height":"Visina",
"Help":"Pomoć",
"Hex color code":"HEX kod boje",
"Hidden":"Skriveno",
"Horizontal align":"Horizontalno poravnanje",
"Horizontal line":"Horizontalna linija",
"Horizontal space":"Horizontalni razmak",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID treba počinjati slovom, praćenim samo slovima, brojevima, crticama, točkama, dvotočkama ili podvlačenjima.",
"Image is decorative":"Slika je dekorativna",
"Image list":"Lista slika",
"Image title":"Naslov slike",
"Image...":"Slika...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP greška ImageProxy: Nije moguće pronaći Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP greška ImageProxy: Netočan URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP greška ImageProxy: Odbijen zahtjev",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP greška ImageProxy: Nepoznata greška ImageProxy",
"Increase indent":"Povećaj uvlačenje",
"Inline":"Ugrađeno",
"Insert":"Umetni",
"Insert Template":"Umetni šablon",
"Insert accordion":"",
"Insert column after":"Umetni kolonu desno",
"Insert column before":"Umetni kolonu lijevo",
"Insert date/time":"Umetni datum/vrijeme",
"Insert image":"Umetni sliku",
"Insert link (if link plugin activated)":"Umetni link (ako je plugin link aktiviran)",
"Insert row after":"Umetni red dolje",
"Insert row before":"Umetni red gore",
"Insert table":"Umetni tabelu",
"Insert template...":"Umetni šablon...",
"Insert video":"Umetni video",
"Insert/Edit code sample":"Dodaj/Uredi primjer koda",
"Insert/edit image":"Umetni/uredi sliku",
"Insert/edit link":"Umetni/uredi link",
"Insert/edit media":"Umetni/uredi medije",
"Insert/edit video":"Umetni/uredi video",
"Inset":"Umetak",
"Invalid hex color code: {0}":"Nevaljan HEX kod boje: {0}",
"Invalid input":"Nevaljan unos",
"Italic":"Kurziv",
"Justify":"Poravnaj po širini",
"Keyboard Navigation":"Navigacija tipkovnicom",
"Language":"Jezik",
"Learn more...":"Saznaj više...",
"Left":"Lijevo",
"Left to right":"S lijeva na desno",
"Light Blue":"Svjetlo plava",
"Light Gray":"Svjetlo siva",
"Light Green":"Svjetlo zelena",
"Light Purple":"Svjetlo ljubičasta",
"Light Red":"Svjetlo crvena",
"Light Yellow":"Svjetlo žuta",
"Line height":"Visina linije",
"Link list":"Lista linkova",
"Link...":"Link...",
"List Properties":"Svojstva liste",
"List properties...":"Svojstva liste...",
"Loading emojis...":"Učitavanje emojija...",
"Loading...":"Učitavanje...",
"Lower Alpha":"Mala slova",
"Lower Greek":"Mali grčki",
"Lower Roman":"Mali rimski",
"Match case":"Usporedi velika/mala slova",
"Mathematical":"Matematički",
"Media poster (Image URL)":"Poster medija (URL slike)",
"Media...":"Mediji...",
"Medium Blue":"Srednje plava",
"Medium Gray":"Srednje siva",
"Medium Purple":"Srednje ljubičasta",
"Merge cells":"Spoji ćelije",
"Middle":"Sredina",
"Midnight Blue":"Ponoćno plava",
"More...":"Više...",
"Name":"Ime",
"Navy Blue":"Mornarsko plava",
"New document":"Novi dokument",
"New window":"Novi prozor",
"Next":"Sljedeći",
"No":"Ne",
"No alignment":"Bez poravnanja",
"No color":"Bez boje",
"Nonbreaking space":"Nerazdvojni razmak",
"None":"Nijedan",
"Numbered list":"Numerisana lista",
"OR":"ILI",
"Objects":"Objekti",
"Ok":"OK",
"Open help dialog":"Otvori dijaloški okvir pomoći",
"Open link":"Otvori link",
"Open link in...":"Otvori link u...",
"Open popup menu for split buttons":"Otvori popup meni za podijeljene tipke",
"Orange":"Narančasta",
"Outset":"Izdubljenje",
"Page break":"Prijelom stranice",
"Paragraph":"Paragraf",
"Paste":"Zalijepi",
"Paste as text":"Zalijepi kao tekst",
"Paste column after":"Zalijepi kolonu desno",
"Paste column before":"Zalijepi kolonu lijevo",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Lijepljenje je sada u načinu običnog teksta. Sadržaj će se zalijepiti kao običan tekst dok ne isključite ovu opciju.",
"Paste or type a link":"Zalijepite ili upišite link",
"Paste row after":"Zalijepi red dolje",
"Paste row before":"Zalijepi red gore",
"Paste your embed code below:":"Zalijepite svoj ugrađeni kod ispod:",
"People":"Ljudi",
"Plugins":"Pluginovi",
"Plugins installed ({0}):":"Instalirani pluginovi ({0}):",
"Powered by {0}":"Pokreće {0}",
"Pre":"Pre",
"Preferences":"Preference",
"Preformatted":"Unaprijed formatiran",
"Premium plugins:":"Premium pluginovi:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Pregled",
"Previous":"Prethodni",
"Print":"Ispis",
"Print...":"Ispis...",
"Purple":"Ljubičasta",
"Quotations":"Citat",
"R":"R",
"Range 0 to 255":"Raspon 0 do 255",
"Red":"Crvena",
"Red component":"Crvena komponenta",
"Redo":"Ponovi",
"Remove":"Ukloni",
"Remove color":"Ukloni boju",
"Remove link":"Ukloni link",
"Replace":"Zamijeni",
"Replace all":"Zamijeni sve",
"Replace with":"Zamijeni sa",
"Resize":"Promijeni veličinu",
"Restore last draft":"Vrati posljednju skicu",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Područje obogaćenog teksta",
"Rich Text Area. Press ALT-0 for help.":"Područje obogaćenog teksta. Pritisnite ALT-0 za pomoć.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Područje obogaćenog teksta. Pritisnite ALT-F9 za meni, ALT-F10 za traku alata, ALT-0 za pomoć",
"Ridge":"Greben",
"Right":"Desno",
"Right to left":"S desna na lijevo",
"Row":"Red",
"Row clipboard actions":"Akcije međuspremnika za red",
"Row group":"Grupa redova",
"Row header":"Zaglavlje reda",
"Row properties":"Svojstva reda",
"Row type":"Tip reda",
"Rows":"Redovi",
"Save":"Spremi",
"Save (if save plugin activated)":"Spremi (ako je plugin save aktiviran)",
"Scope":"Opseg",
"Search":"Pretraži",
"Select all":"Odaberi sve",
"Select...":"Odaberi...",
"Selection":"Odabir",
"Shortcut":"Prečac",
"Show blocks":"Prikaži blokove",
"Show caption":"Prikaži naslov",
"Show invisible characters":"Prikaži nevidljive znakove",
"Size":"Veličina",
"Solid":"Puna",
"Source":"Izvor",
"Source code":"Izvorni kod",
"Special Character":"Specijalni znak",
"Special character...":"Specijalni znak...",
"Split cell":"Podijeli ćeliju",
"Square":"Kvadrat",
"Start list at number":"Počni numeraciju od",
"Strikethrough":"Precrtano",
"Style":"Stil",
"Subscript":"Indeks",
"Superscript":"Eksponent",
"Switch to or from fullscreen mode":"Prebaci u ili iz načina punog ekrana",
"Symbols":"Simboli",
"System Font":"Sistemski font",
"Table":"Tabela",
"Table caption":"Naslov tabele",
"Table properties":"Svojstva tabele",
"Table styles":"Stilovi tabele",
"Template":"Šablon",
"Templates":"Šabloni",
"Text":"Tekst",
"Text color":"Boja teksta",
"Text color {0}":"",
"Text to display":"Tekst za prikaz",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL koji ste unijeli izgleda kao email adresa. Želite li dodati potreban mailto: prefiks?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL koji ste unijeli izgleda kao vanjski link. Želite li dodati potreban http:// prefiks?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL koji ste unijeli izgleda kao vanjski link. Želite li dodati potreban https:// prefiks?",
"Title":"Naslov",
"To open the popup, press Shift+Enter":"Za otvaranje popup menija, pritisnite Shift+Enter",
"Toggle accordion":"",
"Tools":"Alati",
"Top":"Vrh",
"Travel and Places":"Putovanja i mjesta",
"Turquoise":"Tirkizna",
"Underline":"Podvučeno",
"Undo":"Poništi",
"Upload":"Učitaj",
"Uploading image":"Učitavanje slike",
"Upper Alpha":"Velika slova",
"Upper Roman":"Veliki rimski",
"Url":"URL",
"User Defined":"Definirano od strane korisnika",
"Valid":"Valjan",
"Version":"Verzija",
"Vertical align":"Vertikalno poravnanje",
"Vertical space":"Vertikalni razmak",
"View":"Pregled",
"Visual aids":"Vizualne pomoći",
"Warn":"Upozorenje",
"White":"Bijela",
"Width":"Širina",
"Word count":"Broj riječi",
"Words":"Riječi",
"Words: {0}":"Riječi: {0}",
"Yellow":"Žuta",
"Yes":"Da",
"You are using {0}":"Koristite {0}",
"You have unsaved changes are you sure you want to navigate away?":"Imate nesačuvane promjene. Jeste li sigurni da želite otići?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Vaš preglednik ne podržava direktan pristup međuspremniku. Molimo koristite Ctrl+X/C/V prečace tipkovnice.",
"alignment":"poravnanje",
"austral sign":"znak austral",
"cedi sign":"znak cedi",
"colon sign":"dvotočka",
"cruzeiro sign":"znak cruzeiro",
"currency sign":"znak valute",
"dollar sign":"znak dolara",
"dong sign":"znak dong",
"drachma sign":"znak drahme",
"euro-currency sign":"znak eura",
"example":"primjer",
"formatting":"formatiranje",
"french franc sign":"znak francuskog franka",
"german penny symbol":"znak njemačkog penija",
"guarani sign":"znak guarani",
"history":"povijest",
"hryvnia sign":"znak grivne",
"indentation":"uvlačenje",
"indian rupee sign":"znak indijske rupije",
"kip sign":"znak kip",
"lira sign":"znak lire",
"livre tournois sign":"znak livre tournois",
"manat sign":"znak manata",
"mill sign":"znak mila",
"naira sign":"znak naira",
"new sheqel sign":"znak novog šekela",
"nordic mark sign":"znak nordijske marke",
"peseta sign":"znak pesete",
"peso sign":"znak pesa",
"ruble sign":"znak rublje",
"rupee sign":"znak rupije",
"spesmilo sign":"znak spesmilo",
"styles":"stilovi",
"tenge sign":"znak tenge",
"tugrik sign":"znak tugrika",
"turkish lira sign":"znak turske lire",
"won sign":"znak wona",
"yen character":"znak jene",
"yen/yuan character variant one":"znak jene/juana, varijanta 1",
"yuan character":"znak juana",
"yuan character, in hong kong and taiwan":"znak juana, Hong Kong i Tajvan",
"{0} characters":"{0} znakova",
"{0} columns, {1} rows":"",
"{0} words":"{0} riječi"
});
