tinymce.addI18n("cs",{
"#":"#",
"Accessibility":"Přístupnost",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Akce",
"Activity":"Aktivita",
"Address":"Adresa",
"Advanced":"Pokročilé",
"Align":"Zarovnat",
"Align center":"Zarovnat na střed",
"Align left":"Zarovnat vlevo",
"Align right":"Zarovnat vpravo",
"Alignment":"Zarovnání",
"Alignment {0}":"",
"All":"Vše",
"Alternative description":"Alternativní popis",
"Alternative source":"Alternativní zdroj",
"Alternative source URL":"URL alternativního zdroje",
"Anchor":"Kotva",
"Anchor...":"Kotva...",
"Anchors":"Kotvy",
"Animals and Nature":"Zvířata a příroda",
"Arrows":"Šipky",
"B":"B",
"Background color":"Barva pozadí",
"Background color {0}":"",
"Black":"Černá",
"Block":"Blok",
"Block {0}":"",
"Blockquote":"Bloková citace",
"Blocks":"Bloky",
"Blue":"Modrá",
"Blue component":"Modrá složka",
"Body":"Tělo",
"Bold":"Tučné",
"Border":"Okraj",
"Border color":"Barva okraje",
"Border style":"Styl okraje",
"Border width":"Šířka okraje",
"Bottom":"Dole",
"Browse files":"",
"Browse for an image":"Procházet obrázky",
"Browse links":"",
"Bullet list":"Seznam s odrážkami",
"Cancel":"Zrušit",
"Caption":"Popisek",
"Cell":"Buňka",
"Cell padding":"Vnitřní odsazení buňky",
"Cell properties":"Vlastnosti buňky",
"Cell spacing":"Vnější odsazení buňky",
"Cell styles":"Styly buňky",
"Cell type":"Typ buňky",
"Center":"Střed",
"Characters":"Znaky",
"Characters (no spaces)":"Znaky (bez mezer)",
"Circle":"Kruh",
"Class":"Třída",
"Clear formatting":"Vymazat formátování",
"Close":"Zavřít",
"Code":"Kód",
"Code sample...":"Ukázka kódu...",
"Code view":"Zobrazení kódu",
"Color Picker":"Výběr barvy",
"Color swatch":"Vzorek barvy",
"Cols":"Sloupce",
"Column":"Sloupec",
"Column clipboard actions":"Akce schránky pro sloupec",
"Column group":"Skupina sloupců",
"Column header":"Záhlaví sloupce",
"Constrain proportions":"Omezit proporce",
"Copy":"Kopírovat",
"Copy column":"Kopírovat sloupec",
"Copy row":"Kopírovat řádek",
"Could not find the specified string.":"Nelze najít zadaný řetězec.",
"Could not load emojis":"Nelze načíst emoji",
"Count":"Počet",
"Currency":"Měna",
"Current window":"Aktuální okno",
"Custom color":"Vlastní barva",
"Custom...":"Vlastní...",
"Cut":"Vyříznout",
"Cut column":"Vyříznout sloupec",
"Cut row":"Vyříznout řádek",
"Dark Blue":"Tmavě modrá",
"Dark Gray":"Tmavě šedá",
"Dark Green":"Tmavě zelená",
"Dark Orange":"Tmavě oranžová",
"Dark Purple":"Tmavě fialová",
"Dark Red":"Tmavě červená",
"Dark Turquoise":"Tmavě tyrkysová",
"Dark Yellow":"Tmavě žlutá",
"Dashed":"Čárkovaná",
"Date/time":"Datum/čas",
"Decrease indent":"Zmenšit odsazení",
"Default":"Výchozí",
"Delete accordion":"",
"Delete column":"Smazat sloupec",
"Delete row":"Smazat řádek",
"Delete table":"Smazat tabulku",
"Dimensions":"Rozměry",
"Disc":"Disk",
"Div":"Div",
"Document":"Dokument",
"Dotted":"Tečkovaná",
"Double":"Dvojitá",
"Drop an image here":"Sem přetáhněte obrázek",
"Dropped file type is not supported":"Typ souboru není podporován",
"Edit":"Upravit",
"Embed":"Vložený",
"Emojis":"Emoji",
"Emojis...":"Emoji...",
"Error":"Chyba",
"Error: Form submit field collision.":"Chyba: Kolize polí pro odeslání formuláře.",
"Error: No form element found.":"Chyba: Nenalezen element formuláře.",
"Extended Latin":"Rozšířená latinka",
"Failed to initialize plugin: {0}":"Chyba při inicializaci pluginu: {0}",
"Failed to load plugin url: {0}":"Chyba při načítání URL pluginu: {0}",
"Failed to load plugin: {0} from url {1}":"Chyba při načítání pluginu: {0} z URL {1}",
"Failed to upload image: {0}":"Chyba při nahrávání obrázku: {0}",
"File":"Soubor",
"Find":"Najít",
"Find (if searchreplace plugin activated)":"Najít (pokud je plugin searchreplace aktivován)",
"Find and Replace":"Najít a nahradit",
"Find and replace...":"Najít a nahradit...",
"Find in selection":"Hledat ve výběru",
"Find whole words only":"Najít pouze celá slova",
"Flags":"Vlajky",
"Focus to contextual toolbar":"Zaměřit na kontextovou lištu nástrojů",
"Focus to element path":"Zaměřit na cestu elementu",
"Focus to menubar":"Zaměřit na lištu menu",
"Focus to toolbar":"Zaměřit na lištu nástrojů",
"Font":"Písmo",
"Font size {0}":"",
"Font sizes":"Velikosti písma",
"Font {0}":"",
"Fonts":"Písma",
"Food and Drink":"Jídlo a pití",
"Footer":"Zápatí",
"Format":"Formát",
"Format {0}":"",
"Formats":"Formáty",
"Fullscreen":"Celá obrazovka",
"G":"G",
"General":"Obecné",
"Gray":"Šedá",
"Green":"Zelená",
"Green component":"Zelená složka",
"Groove":"Drážka",
"Handy Shortcuts":"Užitečné klávesové zkratky",
"Header":"Záhlaví",
"Header cell":"Buňka záhlaví",
"Heading 1":"Nadpis 1",
"Heading 2":"Nadpis 2",
"Heading 3":"Nadpis 3",
"Heading 4":"Nadpis 4",
"Heading 5":"Nadpis 5",
"Heading 6":"Nadpis 6",
"Headings":"Nadpisy",
"Height":"Výška",
"Help":"Nápověda",
"Hex color code":"HEX kód barvy",
"Hidden":"Skrytý",
"Horizontal align":"Horizontální zarovnání",
"Horizontal line":"Horizontální čára",
"Horizontal space":"Horizontální mezera",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID by mělo začínat písmenem, následované pouze písmeny, čísly, pomlčkami, tečkami, dvojtečkami nebo podtržítky.",
"Image is decorative":"Obrázek je dekorativní",
"Image list":"Seznam obrázků",
"Image title":"Název obrázku",
"Image...":"Obrázek...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP chyba ImageProxy: Nelze najít Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP chyba ImageProxy: Nesprávný URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP chyba ImageProxy: Odmítnutý požadavek",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP chyba ImageProxy: Neznámá chyba ImageProxy",
"Increase indent":"Zvětšit odsazení",
"Inline":"Vložený",
"Insert":"Vložit",
"Insert Template":"Vložit šablonu",
"Insert accordion":"",
"Insert column after":"Vložit sloupec vpravo",
"Insert column before":"Vložit sloupec vlevo",
"Insert date/time":"Vložit datum/čas",
"Insert image":"Vložit obrázek",
"Insert link (if link plugin activated)":"Vložit odkaz (pokud je plugin link aktivován)",
"Insert row after":"Vložit řádek dolů",
"Insert row before":"Vložit řádek nahoru",
"Insert table":"Vložit tabulku",
"Insert template...":"Vložit šablonu...",
"Insert video":"Vložit video",
"Insert/Edit code sample":"Přidat/upravit ukázku kódu",
"Insert/edit image":"Vložit/upravit obrázek",
"Insert/edit link":"Vložit/upravit odkaz",
"Insert/edit media":"Vložit/upravit média",
"Insert/edit video":"Vložit/upravit video",
"Inset":"Vložka",
"Invalid hex color code: {0}":"Neplatný HEX kód barvy: {0}",
"Invalid input":"Neplatný vstup",
"Italic":"Kurzíva",
"Justify":"Zarovnat do bloku",
"Keyboard Navigation":"Navigace klávesnicí",
"Language":"Jazyk",
"Learn more...":"Dozvědět se více...",
"Left":"Vlevo",
"Left to right":"Zleva doprava",
"Light Blue":"Světle modrá",
"Light Gray":"Světle šedá",
"Light Green":"Světle zelená",
"Light Purple":"Světle fialová",
"Light Red":"Světle červená",
"Light Yellow":"Světle žlutá",
"Line height":"Výška řádku",
"Link list":"Seznam odkazů",
"Link...":"Odkaz...",
"List Properties":"Vlastnosti seznamu",
"List properties...":"Vlastnosti seznamu...",
"Loading emojis...":"Načítání emoji...",
"Loading...":"Načítání...",
"Lower Alpha":"Malá písmena",
"Lower Greek":"Malá řecká",
"Lower Roman":"Malá římská",
"Match case":"Rozlišovat velikost písmen",
"Mathematical":"Matematické",
"Media poster (Image URL)":"Plakát média (URL obrázku)",
"Media...":"Média...",
"Medium Blue":"Středně modrá",
"Medium Gray":"Středně šedá",
"Medium Purple":"Středně fialová",
"Merge cells":"Sloučit buňky",
"Middle":"Střed",
"Midnight Blue":"Půlnoční modrá",
"More...":"Více...",
"Name":"Název",
"Navy Blue":"Námořnická modrá",
"New document":"Nový dokument",
"New window":"Nové okno",
"Next":"Další",
"No":"Ne",
"No alignment":"Bez zarovnání",
"No color":"Bez barvy",
"Nonbreaking space":"Nerozdělitelná mezera",
"None":"Žádný",
"Numbered list":"Číslovaný seznam",
"OR":"NEBO",
"Objects":"Objekty",
"Ok":"OK",
"Open help dialog":"Otevřít dialog nápovědy",
"Open link":"Otevřít odkaz",
"Open link in...":"Otevřít odkaz v...",
"Open popup menu for split buttons":"Otevřít vyskakovací menu pro rozdělená tlačítka",
"Orange":"Oranžová",
"Outset":"Výřez",
"Page break":"Zalomení stránky",
"Paragraph":"Odstavec",
"Paste":"Vložit",
"Paste as text":"Vložit jako text",
"Paste column after":"Vložit sloupec vpravo",
"Paste column before":"Vložit sloupec vlevo",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Vkládání je nyní v režimu prostého textu. Obsah bude vkládán jako prostý text, dokud tuto možnost nevypnete.",
"Paste or type a link":"Vložte nebo napište odkaz",
"Paste row after":"Vložit řádek dolů",
"Paste row before":"Vložit řádek nahoru",
"Paste your embed code below:":"Vložte svůj vložený kód níže:",
"People":"Lidé",
"Plugins":"Pluginy",
"Plugins installed ({0}):":"Nainstalované pluginy ({0}):",
"Powered by {0}":"Poháněno {0}",
"Pre":"Pre",
"Preferences":"Předvolby",
"Preformatted":"Předformátovaný",
"Premium plugins:":"Prémiové pluginy:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Náhled",
"Previous":"Předchozí",
"Print":"Tisk",
"Print...":"Tisk...",
"Purple":"Fialová",
"Quotations":"Citace",
"R":"R",
"Range 0 to 255":"Rozsah 0 až 255",
"Red":"Červená",
"Red component":"Červená složka",
"Redo":"Znovu",
"Remove":"Odstranit",
"Remove color":"Odstranit barvu",
"Remove link":"Odstranit odkaz",
"Replace":"Nahradit",
"Replace all":"Nahradit vše",
"Replace with":"Nahradit za",
"Resize":"Změnit velikost",
"Restore last draft":"Obnovit poslední koncept",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Oblast formátovaného textu",
"Rich Text Area. Press ALT-0 for help.":"Oblast formátovaného textu. Stiskněte ALT-0 pro nápovědu.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Oblast formátovaného textu. Stiskněte ALT-F9 pro menu, ALT-F10 pro lištu nástrojů, ALT-0 pro nápovědu",
"Ridge":"Hřeben",
"Right":"Vpravo",
"Right to left":"Zprava doleva",
"Row":"Řádek",
"Row clipboard actions":"Akce schránky pro řádek",
"Row group":"Skupina řádků",
"Row header":"Záhlaví řádku",
"Row properties":"Vlastnosti řádku",
"Row type":"Typ řádku",
"Rows":"Řádky",
"Save":"Uložit",
"Save (if save plugin activated)":"Uložit (pokud je plugin save aktivován)",
"Scope":"Rozsah",
"Search":"Hledat",
"Select all":"Vybrat vše",
"Select...":"Vybrat...",
"Selection":"Výběr",
"Shortcut":"Klávesová zkratka",
"Show blocks":"Zobrazit bloky",
"Show caption":"Zobrazit popisek",
"Show invisible characters":"Zobrazit neviditelné znaky",
"Size":"Velikost",
"Solid":"Plná",
"Source":"Zdroj",
"Source code":"Zdrojový kód",
"Special Character":"Speciální znak",
"Special character...":"Speciální znak...",
"Split cell":"Rozdělit buňku",
"Square":"Čtverec",
"Start list at number":"Začít číslování od",
"Strikethrough":"Přeškrtnuté",
"Style":"Styl",
"Subscript":"Dolní index",
"Superscript":"Horní index",
"Switch to or from fullscreen mode":"Přepnout do nebo z režimu celé obrazovky",
"Symbols":"Symboly",
"System Font":"Systémové písmo",
"Table":"Tabulka",
"Table caption":"Popisek tabulky",
"Table properties":"Vlastnosti tabulky",
"Table styles":"Styly tabulky",
"Template":"Šablona",
"Templates":"Šablony",
"Text":"Text",
"Text color":"Barva textu",
"Text color {0}":"",
"Text to display":"Text k zobrazení",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL, který jste zadali, vypadá jako emailová adresa. Chcete přidat požadovaný prefix mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL, který jste zadali, vypadá jako externí odkaz. Chcete přidat požadovaný prefix http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL, který jste zadali, vypadá jako externí odkaz. Chcete přidat požadovaný prefix https://?",
"Title":"Název",
"To open the popup, press Shift+Enter":"Pro otevření vyskakovacího menu stiskněte Shift+Enter",
"Toggle accordion":"",
"Tools":"Nástroje",
"Top":"Nahoru",
"Travel and Places":"Cestování a místa",
"Turquoise":"Tyrkysová",
"Underline":"Podtržené",
"Undo":"Zpět",
"Upload":"Nahrát",
"Uploading image":"Nahrávání obrázku",
"Upper Alpha":"Velká písmena",
"Upper Roman":"Velká římská",
"Url":"URL",
"User Defined":"Definováno uživatelem",
"Valid":"Platný",
"Version":"Verze",
"Vertical align":"Vertikální zarovnání",
"Vertical space":"Vertikální mezera",
"View":"Zobrazení",
"Visual aids":"Vizuální pomůcky",
"Warn":"Varování",
"White":"Bílá",
"Width":"Šířka",
"Word count":"Počet slov",
"Words":"Slova",
"Words: {0}":"Slova: {0}",
"Yellow":"Žlutá",
"Yes":"Ano",
"You are using {0}":"Používáte {0}",
"You have unsaved changes are you sure you want to navigate away?":"Máte neuložené změny. Jste si jisti, že chcete odejít?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Váš prohlížeč nepodporuje přímý přístup ke schránce. Místo toho použijte klávesové zkratky Ctrl+X/C/V.",
"alignment":"zarovnání",
"austral sign":"znak austral",
"cedi sign":"znak cedi",
"colon sign":"dvojtečka",
"cruzeiro sign":"znak cruzeiro",
"currency sign":"znak měny",
"dollar sign":"znak dolaru",
"dong sign":"znak dong",
"drachma sign":"znak drachmy",
"euro-currency sign":"znak eura",
"example":"příklad",
"formatting":"formátování",
"french franc sign":"znak francouzského franku",
"german penny symbol":"znak německého feniku",
"guarani sign":"znak guarani",
"history":"historie",
"hryvnia sign":"znak hřivny",
"indentation":"odsazení",
"indian rupee sign":"znak indické rupie",
"kip sign":"znak kip",
"lira sign":"znak liry",
"livre tournois sign":"znak livre tournois",
"manat sign":"znak manatu",
"mill sign":"znak mil",
"naira sign":"znak naira",
"new sheqel sign":"znak nového šekelu",
"nordic mark sign":"znak nordické marky",
"peseta sign":"znak pesety",
"peso sign":"znak pesa",
"ruble sign":"znak rublu",
"rupee sign":"znak rupie",
"spesmilo sign":"znak spesmilo",
"styles":"styly",
"tenge sign":"znak tenge",
"tugrik sign":"znak tugriku",
"turkish lira sign":"znak turecké liry",
"won sign":"znak wonu",
"yen character":"znak jenu",
"yen/yuan character variant one":"znak jenu/juana, varianta 1",
"yuan character":"znak juana",
"yuan character, in hong kong and taiwan":"znak juana, Hong Kong a Tchaj-wan",
"{0} characters":"{0} znaků",
"{0} columns, {1} rows":"",
"{0} words":"{0} slov"
});
