tinymce.addI18n("mk",{
"#":"#",
"Accessibility":"Пристапност",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Акција",
"Activity":"Активност",
"Address":"Адреса",
"Advanced":"Напредно",
"Align":"Порамни",
"Align center":"Центрирај",
"Align left":"Порамни лево",
"Align right":"Порамни десно",
"Alignment":"Порамнување",
"Alignment {0}":"",
"All":"Сите",
"Alternative description":"Алтернативен опис",
"Alternative source":"Алтернативен извор",
"Alternative source URL":"URL на алтернативен извор",
"Anchor":"Сидро",
"Anchor...":"Сидро...",
"Anchors":"Сидриња",
"Animals and Nature":"Животни и природа",
"Arrows":"Стрелки",
"B":"B",
"Background color":"Боја на позадина",
"Background color {0}":"",
"Black":"Црна",
"Block":"Блок",
"Block {0}":"",
"Blockquote":"Блок цитат",
"Blocks":"Блокови",
"Blue":"Сина",
"Blue component":"Сина компонента",
"Body":"Тело",
"Bold":"Здебелено",
"Border":"Граница",
"Border color":"Боја на граница",
"Border style":"Стил на граница",
"Border width":"Ширина на граница",
"Bottom":"Долу",
"Browse files":"",
"Browse for an image":"Пребарај слика",
"Browse links":"",
"Bullet list":"Список со точки",
"Cancel":"Откажи",
"Caption":"Наслов",
"Cell":"Ќелија",
"Cell padding":"Внатрешен одстъп на ќелијата",
"Cell properties":"Својства на ќелијата",
"Cell spacing":"Надворешен одстъп на ќелијата",
"Cell styles":"Стилови на ќелијата",
"Cell type":"Тип на ќелијата",
"Center":"Центар",
"Characters":"Знаци",
"Characters (no spaces)":"Знаци (без празни места)",
"Circle":"Круг",
"Class":"Класа",
"Clear formatting":"Исчисти форматирање",
"Close":"Затвори",
"Code":"Код",
"Code sample...":"Пример за код...",
"Code view":"Преглед на код",
"Color Picker":"Избор на боја",
"Color swatch":"Примерок на боја",
"Cols":"Колони",
"Column":"Колона",
"Column clipboard actions":"Акции на табла за колона",
"Column group":"Група колони",
"Column header":"Заглавје на колона",
"Constrain proportions":"Ограничи пропорции",
"Copy":"Копирај",
"Copy column":"Копирај колона",
"Copy row":"Копирај ред",
"Could not find the specified string.":"Не може да се најде наведениот стринг.",
"Could not load emojis":"Не може да се вчитаат емоции",
"Count":"Број",
"Currency":"Валута",
"Current window":"Тековен прозорец",
"Custom color":"Прилагодена боја",
"Custom...":"Прилагодено...",
"Cut":"Исечи",
"Cut column":"Исечи колона",
"Cut row":"Исечи ред",
"Dark Blue":"Темносина",
"Dark Gray":"Темносива",
"Dark Green":"Темнозелена",
"Dark Orange":"Темно портокалова",
"Dark Purple":"Темновиолетова",
"Dark Red":"Темноцрвена",
"Dark Turquoise":"Темно тиркизна",
"Dark Yellow":"Темножолта",
"Dashed":"Испрекината",
"Date/time":"Датум/време",
"Decrease indent":"Намали вовлекување",
"Default":"Стандардно",
"Delete accordion":"",
"Delete column":"Избриши колона",
"Delete row":"Избриши ред",
"Delete table":"Избриши табела",
"Dimensions":"Димензии",
"Disc":"Диск",
"Div":"Div",
"Document":"Документ",
"Dotted":"Точки",
"Double":"Двојна",
"Drop an image here":"Тука испушти слика",
"Dropped file type is not supported":"Типот на датотека не е поддржан",
"Edit":"Уреди",
"Embed":"Вградено",
"Emojis":"Емоции",
"Emojis...":"Емоции...",
"Error":"Грешка",
"Error: Form submit field collision.":"Грешка: Судир на полиња за испраќање на форма.",
"Error: No form element found.":"Грешка: Не е пронајден елемент на форма.",
"Extended Latin":"Проширена латиница",
"Failed to initialize plugin: {0}":"Неуспешна иницијализација на приклучок: {0}",
"Failed to load plugin url: {0}":"Неуспешно вчитување на URL на приклучок: {0}",
"Failed to load plugin: {0} from url {1}":"Неуспешно вчитување на приклучок: {0} од URL {1}",
"Failed to upload image: {0}":"Неуспешно прикачување на слика: {0}",
"File":"Датотека",
"Find":"Најди",
"Find (if searchreplace plugin activated)":"Најди (ако е активиран приклучок searchreplace)",
"Find and Replace":"Најди и замени",
"Find and replace...":"Најди и замени...",
"Find in selection":"Пребарај во избор",
"Find whole words only":"Најди само цели зборови",
"Flags":"Знамиња",
"Focus to contextual toolbar":"Фокус на контекстуална лента со алатки",
"Focus to element path":"Фокус на патека на елемент",
"Focus to menubar":"Фокус на лента со менија",
"Focus to toolbar":"Фокус на лента со алатки",
"Font":"Фонт",
"Font size {0}":"",
"Font sizes":"Големини на фонт",
"Font {0}":"",
"Fonts":"Фонтови",
"Food and Drink":"Храна и пијалоци",
"Footer":"Подножје",
"Format":"Формат",
"Format {0}":"",
"Formats":"Формати",
"Fullscreen":"Полн екран",
"G":"G",
"General":"Општо",
"Gray":"Сива",
"Green":"Зелена",
"Green component":"Зелена компонента",
"Groove":"Жлеб",
"Handy Shortcuts":"Корисни кратенки",
"Header":"Заглавје",
"Header cell":"Ќелија на заглавје",
"Heading 1":"Наслов 1",
"Heading 2":"Наслов 2",
"Heading 3":"Наслов 3",
"Heading 4":"Наслов 4",
"Heading 5":"Наслов 5",
"Heading 6":"Наслов 6",
"Headings":"Наслови",
"Height":"Висина",
"Help":"Помош",
"Hex color code":"HEX код на боја",
"Hidden":"Скриено",
"Horizontal align":"Хоризонтално порамнување",
"Horizontal line":"Хоризонтална линија",
"Horizontal space":"Хоризонтален простор",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID треба да почне со буква, проследена само со букви, броеви, цртички, точки, двоточки или подвлекувања.",
"Image is decorative":"Сликата е декоративна",
"Image list":"Список на слики",
"Image title":"Наслов на слика",
"Image...":"Слика...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP грешка на ImageProxy: Не може да се најде Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP грешка на ImageProxy: Неточен URL на Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP грешка на ImageProxy: Одбиен барање",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP грешка на ImageProxy: Непозната грешка на ImageProxy",
"Increase indent":"Зголеми вовлекување",
"Inline":"Вградено",
"Insert":"Вметни",
"Insert Template":"Вметни шаблон",
"Insert accordion":"",
"Insert column after":"Вметни колона десно",
"Insert column before":"Вметни колона лево",
"Insert date/time":"Вметни датум/време",
"Insert image":"Вметни слика",
"Insert link (if link plugin activated)":"Вметни врска (ако е активиран приклучок link)",
"Insert row after":"Вметни ред долу",
"Insert row before":"Вметни ред горе",
"Insert table":"Вметни табела",
"Insert template...":"Вметни шаблон...",
"Insert video":"Вметни видео",
"Insert/Edit code sample":"Додај/Уреди пример за код",
"Insert/edit image":"Вметни/уреди слика",
"Insert/edit link":"Вметни/уреди врска",
"Insert/edit media":"Вметни/уреди медиуми",
"Insert/edit video":"Вметни/уреди видео",
"Inset":"Вметка",
"Invalid hex color code: {0}":"Неважечки HEX код на боја: {0}",
"Invalid input":"Неважечки внос",
"Italic":"Курзив",
"Justify":"Порамни по ширина",
"Keyboard Navigation":"Навигација со тастатура",
"Language":"Јазик",
"Learn more...":"Дознај повеќе...",
"Left":"Лево",
"Left to right":"Од лево на десно",
"Light Blue":"Светлосина",
"Light Gray":"Светлосива",
"Light Green":"Светлозелена",
"Light Purple":"Светловиолетова",
"Light Red":"Светлоцрвена",
"Light Yellow":"Светложолта",
"Line height":"Висина на линија",
"Link list":"Список на врски",
"Link...":"Врска...",
"List Properties":"Својства на список",
"List properties...":"Својства на список...",
"Loading emojis...":"Вчитување на емоции...",
"Loading...":"Вчитување...",
"Lower Alpha":"Мали букви",
"Lower Greek":"Мали грчки",
"Lower Roman":"Мали римски",
"Match case":"Спореди големи/мали букви",
"Mathematical":"Математички",
"Media poster (Image URL)":"Постер на медиум (URL на слика)",
"Media...":"Медиуми...",
"Medium Blue":"Средно сина",
"Medium Gray":"Средно сива",
"Medium Purple":"Средно виолетова",
"Merge cells":"Спој ќелии",
"Middle":"Средина",
"Midnight Blue":"Полноќно сина",
"More...":"Повеќе...",
"Name":"Име",
"Navy Blue":"Морнарско сина",
"New document":"Нов документ",
"New window":"Нов прозорец",
"Next":"Следно",
"No":"Не",
"No alignment":"Без порамнување",
"No color":"Без боја",
"Nonbreaking space":"Нераскинлив простор",
"None":"Ниту еден",
"Numbered list":"Нумериран список",
"OR":"ИЛИ",
"Objects":"Објекти",
"Ok":"OK",
"Open help dialog":"Отвори дијалог за помош",
"Open link":"Отвори врска",
"Open link in...":"Отвори врска во...",
"Open popup menu for split buttons":"Отвори popup мени за поделени копчиња",
"Orange":"Портокалова",
"Outset":"Изрезка",
"Page break":"Прекин на страница",
"Paragraph":"Параграф",
"Paste":"Залепи",
"Paste as text":"Залепи како текст",
"Paste column after":"Залепи колона десно",
"Paste column before":"Залепи колона лево",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Залепувањето сега е во режим на обичен текст. Содржината ќе се залепи како обичен текст додека не ја исклучите оваа опција.",
"Paste or type a link":"Залепете или внесете врска",
"Paste row after":"Залепи ред долу",
"Paste row before":"Залепи ред горе",
"Paste your embed code below:":"Залепете го вашиот вграден код подолу:",
"People":"Луѓе",
"Plugins":"Приклучоци",
"Plugins installed ({0}):":"Инсталирани приклучоци ({0}):",
"Powered by {0}":"Покренува {0}",
"Pre":"Pre",
"Preferences":"Преференци",
"Preformatted":"Претходно форматиран",
"Premium plugins:":"Премиум приклучоци:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Преглед",
"Previous":"Претходно",
"Print":"Печати",
"Print...":"Печати...",
"Purple":"Виолетова",
"Quotations":"Цитати",
"R":"R",
"Range 0 to 255":"Опсег од 0 до 255",
"Red":"Црвена",
"Red component":"Црвена компонента",
"Redo":"Повтори",
"Remove":"Отстрани",
"Remove color":"Отстрани боја",
"Remove link":"Отстрани врска",
"Replace":"Замени",
"Replace all":"Замени сите",
"Replace with":"Замени со",
"Resize":"Промени големина",
"Restore last draft":"Врати последен нацрт",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Област за обогатен текст",
"Rich Text Area. Press ALT-0 for help.":"Област за обогатен текст. Притиснете ALT-0 за помош.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Област за обогатен текст. Притиснете ALT-F9 за мени, ALT-F10 за лента со алатки, ALT-0 за помош",
"Ridge":"Гребен",
"Right":"Десно",
"Right to left":"Од десно на лево",
"Row":"Ред",
"Row clipboard actions":"Акции на табла за ред",
"Row group":"Група редови",
"Row header":"Заглавје на ред",
"Row properties":"Својства на ред",
"Row type":"Тип на ред",
"Rows":"Редови",
"Save":"Зачувај",
"Save (if save plugin activated)":"Зачувај (ако е активиран приклучок save)",
"Scope":"Опсег",
"Search":"Пребарај",
"Select all":"Избери сите",
"Select...":"Избери...",
"Selection":"Избор",
"Shortcut":"Кратенка",
"Show blocks":"Прикажи блокови",
"Show caption":"Прикажи наслов",
"Show invisible characters":"Прикажи невидливи знаци",
"Size":"Големина",
"Solid":"Полна",
"Source":"Извор",
"Source code":"Изворен код",
"Special Character":"Специјален знак",
"Special character...":"Специјален знак...",
"Split cell":"Подели ќелија",
"Square":"Квадрат",
"Start list at number":"Почни нумерација од",
"Strikethrough":"Прецртано",
"Style":"Стил",
"Subscript":"Индекс",
"Superscript":"Експонент",
"Switch to or from fullscreen mode":"Префрли во или од режим на полн екран",
"Symbols":"Симболи",
"System Font":"Системски фонт",
"Table":"Табела",
"Table caption":"Наслов на табела",
"Table properties":"Својства на табела",
"Table styles":"Стилови на табела",
"Template":"Шаблон",
"Templates":"Шаблони",
"Text":"Текст",
"Text color":"Боја на текст",
"Text color {0}":"",
"Text to display":"Текст за приказ",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL-то што го внесовте изгледа како email адреса. Дали сакате да го додадете потребниот mailto: префикс?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL-то што го внесовте изгледа како надворешна врска. Дали сакате да го додадете потребниот http:// префикс?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL-то што го внесовте изгледа како надворешна врска. Дали сакате да го додадете потребниот https:// префикс?",
"Title":"Наслов",
"To open the popup, press Shift+Enter":"За да го отворите popup менито, притиснете Shift+Enter",
"Toggle accordion":"",
"Tools":"Алатки",
"Top":"Горе",
"Travel and Places":"Патувања и места",
"Turquoise":"Тиркизна",
"Underline":"Подвлечено",
"Undo":"Откажи",
"Upload":"Прикачи",
"Uploading image":"Прикачување на слика",
"Upper Alpha":"Големи букви",
"Upper Roman":"Големи римски",
"Url":"URL",
"User Defined":"Дефинирано од корисник",
"Valid":"Важечки",
"Version":"Верзија",
"Vertical align":"Вертикално порамнување",
"Vertical space":"Вертикален простор",
"View":"Преглед",
"Visual aids":"Визуелни помошни средства",
"Warn":"Предупредување",
"White":"Бела",
"Width":"Ширина",
"Word count":"Број на зборови",
"Words":"Зборови",
"Words: {0}":"Зборови: {0}",
"Yellow":"Жолта",
"Yes":"Да",
"You are using {0}":"Користите {0}",
"You have unsaved changes are you sure you want to navigate away?":"Имате незачувани промени. Дали сте сигурни дека сакате да заминете?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Вашиот прелистувач не поддржува директен пристап до таблата. Ве молиме користете ги Ctrl+X/C/V кратенките на тастатурата.",
"alignment":"порамнување",
"austral sign":"знак на австрал",
"cedi sign":"знак на седи",
"colon sign":"двоточка",
"cruzeiro sign":"знак на крузеиро",
"currency sign":"знак на валута",
"dollar sign":"знак на долар",
"dong sign":"знак на донг",
"drachma sign":"знак на драхма",
"euro-currency sign":"знак на евро",
"example":"пример",
"formatting":"форматирање",
"french franc sign":"знак на француски франк",
"german penny symbol":"знак на германски пени",
"guarani sign":"знак на гуарани",
"history":"историја",
"hryvnia sign":"знак на гривна",
"indentation":"вовлекување",
"indian rupee sign":"знак на индиска рупија",
"kip sign":"знак на кип",
"lira sign":"знак на лира",
"livre tournois sign":"знак на ливре",
"manat sign":"знак на манат",
"mill sign":"знак на мил",
"naira sign":"знак на наира",
"new sheqel sign":"знак на нов шекел",
"nordic mark sign":"знак на нордичка марка",
"peseta sign":"знак на песета",
"peso sign":"знак на песо",
"ruble sign":"знак на рубла",
"rupee sign":"знак на рупија",
"spesmilo sign":"знак на спесмило",
"styles":"стилови",
"tenge sign":"знак на тенге",
"tugrik sign":"знак на тугрик",
"turkish lira sign":"знак на турска лира",
"won sign":"знак на вон",
"yen character":"знак на јена",
"yen/yuan character variant one":"знак на јена/јуан, варијанта 1",
"yuan character":"знак на јуан",
"yuan character, in hong kong and taiwan":"знак на јуан, Хонг Конг и Тајван",
"{0} characters":"{0} знаци",
"{0} columns, {1} rows":"",
"{0} words":"{0} зборови"
});
