tinymce.addI18n("pl",{
"#":"#",
"Accessibility":"Dostępność",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Akcja",
"Activity":"Aktywność",
"Address":"Adres",
"Advanced":"Zaawansowane",
"Align":"Wyrównaj",
"Align center":"Wyśrodkuj",
"Align left":"Wyrównaj do lewej",
"Align right":"Wyrównaj do prawej",
"Alignment":"Wyrównanie",
"Alignment {0}":"",
"All":"Wszystkie",
"Alternative description":"Alternatywny opis",
"Alternative source":"Alternatywne źródło",
"Alternative source URL":"URL alternatywnego źródła",
"Anchor":"Kotwica",
"Anchor...":"Kotwica...",
"Anchors":"Kotwice",
"Animals and Nature":"Zwierzęta i przyroda",
"Arrows":"Strzałki",
"B":"B",
"Background color":"Kolor tła",
"Background color {0}":"",
"Black":"Czarny",
"Block":"Blok",
"Block {0}":"",
"Blockquote":"Cytat blokowy",
"Blocks":"Bloki",
"Blue":"Niebieski",
"Blue component":"Składowa niebieska",
"Body":"Treść",
"Bold":"Pogrubienie",
"Border":"Obramowanie",
"Border color":"Kolor obramowania",
"Border style":"Styl obramowania",
"Border width":"Szerokość obramowania",
"Bottom":"Dół",
"Browse files":"",
"Browse for an image":"Przeglądaj obrazy",
"Browse links":"",
"Bullet list":"Lista punktowana",
"Cancel":"Anuluj",
"Caption":"Podpis",
"Cell":"Komórka",
"Cell padding":"Wewnętrzny odstęp komórki",
"Cell properties":"Właściwości komórki",
"Cell spacing":"Zewnętrzny odstęp komórki",
"Cell styles":"Style komórki",
"Cell type":"Typ komórki",
"Center":"Środek",
"Characters":"Znaki",
"Characters (no spaces)":"Znaki (bez spacji)",
"Circle":"Koło",
"Class":"Klasa",
"Clear formatting":"Wyczyść formatowanie",
"Close":"Zamknij",
"Code":"Kod",
"Code sample...":"Przykład kodu...",
"Code view":"Widok kodu",
"Color Picker":"Wybór koloru",
"Color swatch":"Próbka koloru",
"Cols":"Kolumny",
"Column":"Kolumna",
"Column clipboard actions":"Akcje schowka dla kolumny",
"Column group":"Grupa kolumn",
"Column header":"Nagłówek kolumny",
"Constrain proportions":"Ogranicz proporcje",
"Copy":"Kopiuj",
"Copy column":"Kopiuj kolumnę",
"Copy row":"Kopiuj wiersz",
"Could not find the specified string.":"Nie można znaleźć określonego ciągu.",
"Could not load emojis":"Nie można załadować emoji",
"Count":"Liczba",
"Currency":"Waluta",
"Current window":"Bieżące okno",
"Custom color":"Kolor niestandardowy",
"Custom...":"Niestandardowy...",
"Cut":"Wytnij",
"Cut column":"Wytnij kolumnę",
"Cut row":"Wytnij wiersz",
"Dark Blue":"Ciemnoniebieski",
"Dark Gray":"Ciemnoszary",
"Dark Green":"Ciemnozielony",
"Dark Orange":"Ciemnopomarańczowy",
"Dark Purple":"Ciemnofioletowy",
"Dark Red":"Ciemnoczerwony",
"Dark Turquoise":"Ciemnoturkusowy",
"Dark Yellow":"Ciemnożółty",
"Dashed":"Przerywana",
"Date/time":"Data/czas",
"Decrease indent":"Zmniejsz wcięcie",
"Default":"Domyślne",
"Delete accordion":"",
"Delete column":"Usuń kolumnę",
"Delete row":"Usuń wiersz",
"Delete table":"Usuń tabelę",
"Dimensions":"Wymiary",
"Disc":"Dysk",
"Div":"Div",
"Document":"Dokument",
"Dotted":"Kropkowana",
"Double":"Podwójna",
"Drop an image here":"Upuść obraz tutaj",
"Dropped file type is not supported":"Typ pliku nie jest obsługiwany",
"Edit":"Edytuj",
"Embed":"Osadzony",
"Emojis":"Emoji",
"Emojis...":"Emoji...",
"Error":"Błąd",
"Error: Form submit field collision.":"Błąd: Konflikt pól przesyłania formularza.",
"Error: No form element found.":"Błąd: Nie znaleziono elementu formularza.",
"Extended Latin":"Rozszerzona łacina",
"Failed to initialize plugin: {0}":"Nie udało się zainicjować wtyczki: {0}",
"Failed to load plugin url: {0}":"Nie udało się załadować URL wtyczki: {0}",
"Failed to load plugin: {0} from url {1}":"Nie udało się załadować wtyczki: {0} z URL {1}",
"Failed to upload image: {0}":"Nie udało się przesłać obrazu: {0}",
"File":"Plik",
"Find":"Znajdź",
"Find (if searchreplace plugin activated)":"Znajdź (jeśli wtyczka searchreplace jest aktywna)",
"Find and Replace":"Znajdź i zamień",
"Find and replace...":"Znajdź i zamień...",
"Find in selection":"Szukaj w zaznaczeniu",
"Find whole words only":"Znajdź tylko całe słowa",
"Flags":"Flagi",
"Focus to contextual toolbar":"Fokus na kontekstowym pasku narzędzi",
"Focus to element path":"Fokus na ścieżce elementu",
"Focus to menubar":"Fokus na pasku menu",
"Focus to toolbar":"Fokus na pasku narzędzi",
"Font":"Czcionka",
"Font size {0}":"",
"Font sizes":"Rozmiary czcionki",
"Font {0}":"",
"Fonts":"Czcionki",
"Food and Drink":"Jedzenie i napoje",
"Footer":"Stopka",
"Format":"Format",
"Format {0}":"",
"Formats":"Formaty",
"Fullscreen":"Pełny ekran",
"G":"G",
"General":"Ogólne",
"Gray":"Szary",
"Green":"Zielony",
"Green component":"Składowa zielona",
"Groove":"Rynna",
"Handy Shortcuts":"Przydatne skróty",
"Header":"Nagłówek",
"Header cell":"Komórka nagłówka",
"Heading 1":"Nagłówek 1",
"Heading 2":"Nagłówek 2",
"Heading 3":"Nagłówek 3",
"Heading 4":"Nagłówek 4",
"Heading 5":"Nagłówek 5",
"Heading 6":"Nagłówek 6",
"Headings":"Nagłówki",
"Height":"Wysokość",
"Help":"Pomoc",
"Hex color code":"Kod koloru HEX",
"Hidden":"Ukryty",
"Horizontal align":"Wyrównanie poziome",
"Horizontal line":"Linia pozioma",
"Horizontal space":"Odstęp poziomy",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID powinno zaczynać się literą, po której następują tylko litery, cyfry, myślniki, kropki, dwukropki lub podkreślenia.",
"Image is decorative":"Obraz jest dekoracyjny",
"Image list":"Lista obrazów",
"Image title":"Tytuł obrazu",
"Image...":"Obraz...",
"ImageProxy HTTP error: Could not find Image Proxy":"Błąd HTTP ImageProxy: Nie można znaleźć Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"Błąd HTTP ImageProxy: Nieprawidłowy URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"Błąd HTTP ImageProxy: Odrzucone żądanie",
"ImageProxy HTTP error: Unknown ImageProxy error":"Błąd HTTP ImageProxy: Nieznany błąd ImageProxy",
"Increase indent":"Zwiększ wcięcie",
"Inline":"Wbudowany",
"Insert":"Wstaw",
"Insert Template":"Wstaw szablon",
"Insert accordion":"",
"Insert column after":"Wstaw kolumnę po prawej",
"Insert column before":"Wstaw kolumnę po lewej",
"Insert date/time":"Wstaw datę/czas",
"Insert image":"Wstaw obraz",
"Insert link (if link plugin activated)":"Wstaw link (jeśli wtyczka link jest aktywna)",
"Insert row after":"Wstaw wiersz poniżej",
"Insert row before":"Wstaw wiersz powyżej",
"Insert table":"Wstaw tabelę",
"Insert template...":"Wstaw szablon...",
"Insert video":"Wstaw wideo",
"Insert/Edit code sample":"Dodaj/edytuj przykład kodu",
"Insert/edit image":"Wstaw/edytuj obraz",
"Insert/edit link":"Wstaw/edytuj link",
"Insert/edit media":"Wstaw/edytuj media",
"Insert/edit video":"Wstaw/edytuj wideo",
"Inset":"Wstawka",
"Invalid hex color code: {0}":"Nieprawidłowy kod koloru HEX: {0}",
"Invalid input":"Nieprawidłowe dane wejściowe",
"Italic":"Kursywa",
"Justify":"Wyjustuj",
"Keyboard Navigation":"Nawigacja klawiaturą",
"Language":"Język",
"Learn more...":"Dowiedz się więcej...",
"Left":"Lewo",
"Left to right":"Od lewej do prawej",
"Light Blue":"Jasnoniebieski",
"Light Gray":"Jasnoszary",
"Light Green":"Jasnozielony",
"Light Purple":"Jasnofioletowy",
"Light Red":"Jasnoczerwony",
"Light Yellow":"Jasnożółty",
"Line height":"Wysokość linii",
"Link list":"Lista linków",
"Link...":"Link...",
"List Properties":"Właściwości listy",
"List properties...":"Właściwości listy...",
"Loading emojis...":"Ładowanie emoji...",
"Loading...":"Ładowanie...",
"Lower Alpha":"Małe litery",
"Lower Greek":"Małe greckie",
"Lower Roman":"Małe rzymskie",
"Match case":"Uwzględnij wielkość liter",
"Mathematical":"Matematyczne",
"Media poster (Image URL)":"Plakat mediów (URL obrazu)",
"Media...":"Media...",
"Medium Blue":"Średnioniebieski",
"Medium Gray":"Średnioszary",
"Medium Purple":"Średnofioletowy",
"Merge cells":"Scal komórki",
"Middle":"Środek",
"Midnight Blue":"Ciemnoniebieski",
"More...":"Więcej...",
"Name":"Nazwa",
"Navy Blue":"Granatowy",
"New document":"Nowy dokument",
"New window":"Nowe okno",
"Next":"Dalej",
"No":"Nie",
"No alignment":"Brak wyrównania",
"No color":"Bez koloru",
"Nonbreaking space":"Niełamliwa spacja",
"None":"Brak",
"Numbered list":"Lista numerowana",
"OR":"LUB",
"Objects":"Obiekty",
"Ok":"OK",
"Open help dialog":"Otwórz okno pomocy",
"Open link":"Otwórz link",
"Open link in...":"Otwórz link w...",
"Open popup menu for split buttons":"Otwórz menu popup dla podzielonych przycisków",
"Orange":"Pomarańczowy",
"Outset":"Występ",
"Page break":"Podział strony",
"Paragraph":"Akapit",
"Paste":"Wklej",
"Paste as text":"Wklej jako tekst",
"Paste column after":"Wklej kolumnę po prawej",
"Paste column before":"Wklej kolumnę po lewej",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Wklejanie jest teraz w trybie zwykłego tekstu. Treść będzie wklejana jako zwykły tekst, dopóki nie wyłączysz tej opcji.",
"Paste or type a link":"Wklej lub wpisz link",
"Paste row after":"Wklej wiersz poniżej",
"Paste row before":"Wklej wiersz powyżej",
"Paste your embed code below:":"Wklej swój osadzony kod poniżej:",
"People":"Ludzie",
"Plugins":"Wtyczki",
"Plugins installed ({0}):":"Zainstalowane wtyczki ({0}):",
"Powered by {0}":"Napędzane przez {0}",
"Pre":"Pre",
"Preferences":"Preferencje",
"Preformatted":"Wstępnie sformatowany",
"Premium plugins:":"Wtyczki premium:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Podgląd",
"Previous":"Poprzedni",
"Print":"Drukuj",
"Print...":"Drukuj...",
"Purple":"Fioletowy",
"Quotations":"Cytaty",
"R":"R",
"Range 0 to 255":"Zakres 0 do 255",
"Red":"Czerwony",
"Red component":"Składowa czerwona",
"Redo":"Ponów",
"Remove":"Usuń",
"Remove color":"Usuń kolor",
"Remove link":"Usuń link",
"Replace":"Zamień",
"Replace all":"Zamień wszystkie",
"Replace with":"Zamień na",
"Resize":"Zmień rozmiar",
"Restore last draft":"Przywróć ostatni szkic",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Obszar tekstu sformatowanego",
"Rich Text Area. Press ALT-0 for help.":"Obszar tekstu sformatowanego. Naciśnij ALT-0, aby uzyskać pomoc.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Obszar tekstu sformatowanego. Naciśnij ALT-F9 dla menu, ALT-F10 dla paska narzędzi, ALT-0 dla pomocy",
"Ridge":"Grzbiet",
"Right":"Prawo",
"Right to left":"Od prawej do lewej",
"Row":"Wiersz",
"Row clipboard actions":"Akcje schowka dla wiersza",
"Row group":"Grupa wierszy",
"Row header":"Nagłówek wiersza",
"Row properties":"Właściwości wiersza",
"Row type":"Typ wiersza",
"Rows":"Wiersze",
"Save":"Zapisz",
"Save (if save plugin activated)":"Zapisz (jeśli wtyczka save jest aktywna)",
"Scope":"Zakres",
"Search":"Szukaj",
"Select all":"Zaznacz wszystko",
"Select...":"Zaznacz...",
"Selection":"Zaznaczenie",
"Shortcut":"Skrót",
"Show blocks":"Pokaż bloki",
"Show caption":"Pokaż podpis",
"Show invisible characters":"Pokaż niewidoczne znaki",
"Size":"Rozmiar",
"Solid":"Pełny",
"Source":"Źródło",
"Source code":"Kod źródłowy",
"Special Character":"Znak specjalny",
"Special character...":"Znak specjalny...",
"Split cell":"Podziel komórkę",
"Square":"Kwadrat",
"Start list at number":"Rozpocznij numerację od",
"Strikethrough":"Przekreślenie",
"Style":"Styl",
"Subscript":"Indeks dolny",
"Superscript":"Indeks górny",
"Switch to or from fullscreen mode":"Przełącz do lub z trybu pełnoekranowego",
"Symbols":"Symbole",
"System Font":"Czcionka systemowa",
"Table":"Tabela",
"Table caption":"Podpis tabeli",
"Table properties":"Właściwości tabeli",
"Table styles":"Style tabeli",
"Template":"Szablon",
"Templates":"Szablony",
"Text":"Tekst",
"Text color":"Kolor tekstu",
"Text color {0}":"",
"Text to display":"Tekst do wyświetlenia",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"Wprowadzony URL wydaje się być adresem e-mail. Czy chcesz dodać wymagany prefiks mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"Wprowadzony URL wydaje się być zewnętrznym linkiem. Czy chcesz dodać wymagany prefiks http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"Wprowadzony URL wydaje się być zewnętrznym linkiem. Czy chcesz dodać wymagany prefiks https://?",
"Title":"Tytuł",
"To open the popup, press Shift+Enter":"Aby otworzyć menu popup, naciśnij Shift+Enter",
"Toggle accordion":"",
"Tools":"Narzędzia",
"Top":"Góra",
"Travel and Places":"Podróże i miejsca",
"Turquoise":"Turkusowy",
"Underline":"Podkreślenie",
"Undo":"Cofnij",
"Upload":"Prześlij",
"Uploading image":"Przesyłanie obrazu",
"Upper Alpha":"Wielkie litery",
"Upper Roman":"Wielkie rzymskie",
"Url":"URL",
"User Defined":"Zdefiniowane przez użytkownika",
"Valid":"Prawidłowy",
"Version":"Wersja",
"Vertical align":"Wyrównanie pionowe",
"Vertical space":"Odstęp pionowy",
"View":"Widok",
"Visual aids":"Pomoc wizualna",
"Warn":"Ostrzeżenie",
"White":"Biały",
"Width":"Szerokość",
"Word count":"Liczba słów",
"Words":"Słowa",
"Words: {0}":"Słowa: {0}",
"Yellow":"Żółty",
"Yes":"Tak",
"You are using {0}":"Używasz {0}",
"You have unsaved changes are you sure you want to navigate away?":"Masz niezapisane zmiany. Czy na pewno chcesz opuścić stronę?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Twoja przeglądarka nie obsługuje bezpośredniego dostępu do schowka. Użyj zamiast tego skrótów klawiaturowych Ctrl+X/C/V.",
"alignment":"wyrównanie",
"austral sign":"znak austral",
"cedi sign":"znak cedi",
"colon sign":"dwukropek",
"cruzeiro sign":"znak cruzeiro",
"currency sign":"znak waluty",
"dollar sign":"znak dolara",
"dong sign":"znak dong",
"drachma sign":"znak drachmy",
"euro-currency sign":"znak euro",
"example":"przykład",
"formatting":"formatowanie",
"french franc sign":"znak franka francuskiego",
"german penny symbol":"znak feniga niemieckiego",
"guarani sign":"znak guarani",
"history":"historia",
"hryvnia sign":"znak hrywny",
"indentation":"wcięcie",
"indian rupee sign":"znak rupii indyjskiej",
"kip sign":"znak kip",
"lira sign":"znak liry",
"livre tournois sign":"znak livre tournois",
"manat sign":"znak manata",
"mill sign":"znak mil",
"naira sign":"znak naira",
"new sheqel sign":"znak nowego szekla",
"nordic mark sign":"znak marki nordyckiej",
"peseta sign":"znak pesety",
"peso sign":"znak peso",
"ruble sign":"znak rubla",
"rupee sign":"znak rupii",
"spesmilo sign":"znak spesmilo",
"styles":"style",
"tenge sign":"znak tenge",
"tugrik sign":"znak tugrika",
"turkish lira sign":"znak liry tureckiej",
"won sign":"znak wona",
"yen character":"znak jena",
"yen/yuan character variant one":"znak jena/juana, wariant 1",
"yuan character":"znak juana",
"yuan character, in hong kong and taiwan":"znak juana, Hongkong i Tajwan",
"{0} characters":"{0} znaków",
"{0} columns, {1} rows":"",
"{0} words":"{0} słów"
});
