tinymce.addI18n("sk",{
"#":"#",
"Accessibility":"Dostupnosť",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Akcia",
"Activity":"Aktivita",
"Address":"Adresa",
"Advanced":"Pokročilé",
"Align":"Zarovnať",
"Align center":"Zarovnať na stred",
"Align left":"Zarovnať vľavo",
"Align right":"Zarovnať vpravo",
"Alignment":"Zarovnanie",
"Alignment {0}":"",
"All":"Všetky",
"Alternative description":"Alternatívny popis",
"Alternative source":"Alternatívny zdroj",
"Alternative source URL":"URL alternatívneho zdroja",
"Anchor":"Kotva",
"Anchor...":"Kotva...",
"Anchors":"Kotvy",
"Animals and Nature":"Zvieratá a príroda",
"Arrows":"Šípky",
"B":"B",
"Background color":"Farba pozadia",
"Background color {0}":"",
"Black":"Čierna",
"Block":"Blok",
"Block {0}":"",
"Blockquote":"Bloková citácia",
"Blocks":"Bloky",
"Blue":"Modrá",
"Blue component":"Modrá zložka",
"Body":"Telo",
"Bold":"Tučné",
"Border":"Okraj",
"Border color":"Farba okraja",
"Border style":"Štýl okraja",
"Border width":"Šírka okraja",
"Bottom":"Dole",
"Browse files":"",
"Browse for an image":"Prehľadávať obrázky",
"Browse links":"",
"Bullet list":"Zoznam s odrážkami",
"Cancel":"Zrušiť",
"Caption":"Popis",
"Cell":"Bunka",
"Cell padding":"Vnútorné odsadenie bunky",
"Cell properties":"Vlastnosti bunky",
"Cell spacing":"Vonkajšie odsadenie bunky",
"Cell styles":"Štýly bunky",
"Cell type":"Typ bunky",
"Center":"Stred",
"Characters":"Znaky",
"Characters (no spaces)":"Znaky (bez medzier)",
"Circle":"Kruh",
"Class":"Trieda",
"Clear formatting":"Vymazať formátovanie",
"Close":"Zavrieť",
"Code":"Kód",
"Code sample...":"Ukážka kódu...",
"Code view":"Zobrazenie kódu",
"Color Picker":"Výber farby",
"Color swatch":"Vzorka farby",
"Cols":"Stĺpce",
"Column":"Stĺpec",
"Column clipboard actions":"Akcie schránky pre stĺpec",
"Column group":"Skupina stĺpcov",
"Column header":"Záhlavie stĺpca",
"Constrain proportions":"Obmedziť proporcie",
"Copy":"Kopírovať",
"Copy column":"Kopírovať stĺpec",
"Copy row":"Kopírovať riadok",
"Could not find the specified string.":"Nepodarilo sa nájsť zadaný reťazec.",
"Could not load emojis":"Nepodarilo sa načítať emoji",
"Count":"Počet",
"Currency":"Mena",
"Current window":"Aktuálne okno",
"Custom color":"Vlastná farba",
"Custom...":"Vlastné...",
"Cut":"Vystrihnúť",
"Cut column":"Vystrihnúť stĺpec",
"Cut row":"Vystrihnúť riadok",
"Dark Blue":"Tmavomodrá",
"Dark Gray":"Tmavosivá",
"Dark Green":"Tmavozelená",
"Dark Orange":"Tmavooranžová",
"Dark Purple":"Tmavofialová",
"Dark Red":"Tmavočervená",
"Dark Turquoise":"Tmavotyrkysová",
"Dark Yellow":"Tmavožltá",
"Dashed":"Prerušovaná",
"Date/time":"Dátum/čas",
"Decrease indent":"Zmenšiť odsadenie",
"Default":"Predvolené",
"Delete accordion":"",
"Delete column":"Vymazať stĺpec",
"Delete row":"Vymazať riadok",
"Delete table":"Vymazať tabuľku",
"Dimensions":"Rozmery",
"Disc":"Disk",
"Div":"Div",
"Document":"Dokument",
"Dotted":"Bodkovaná",
"Double":"Dvojitá",
"Drop an image here":"Sem pretiahnite obrázok",
"Dropped file type is not supported":"Typ súboru nie je podporovaný",
"Edit":"Upraviť",
"Embed":"Vložený",
"Emojis":"Emoji",
"Emojis...":"Emoji...",
"Error":"Chyba",
"Error: Form submit field collision.":"Chyba: Kolízia polí pre odoslanie formulára.",
"Error: No form element found.":"Chyba: Nenájdený element formulára.",
"Extended Latin":"Rozšírená latinka",
"Failed to initialize plugin: {0}":"Chyba pri inicializácii pluginu: {0}",
"Failed to load plugin url: {0}":"Chyba pri načítaní URL pluginu: {0}",
"Failed to load plugin: {0} from url {1}":"Chyba pri načítaní pluginu: {0} z URL {1}",
"Failed to upload image: {0}":"Chyba pri nahrávaní obrázka: {0}",
"File":"Súbor",
"Find":"Nájsť",
"Find (if searchreplace plugin activated)":"Nájsť (ak je plugin searchreplace aktivovaný)",
"Find and Replace":"Nájsť a nahradiť",
"Find and replace...":"Nájsť a nahradiť...",
"Find in selection":"Hľadať vo výbere",
"Find whole words only":"Nájsť len celé slová",
"Flags":"Vlajky",
"Focus to contextual toolbar":"Zamerať na kontextový panel nástrojov",
"Focus to element path":"Zamerať na cestu elementu",
"Focus to menubar":"Zamerať na panel menu",
"Focus to toolbar":"Zamerať na panel nástrojov",
"Font":"Písmo",
"Font size {0}":"",
"Font sizes":"Veľkosti písma",
"Font {0}":"",
"Fonts":"Písma",
"Food and Drink":"Jedlo a nápoje",
"Footer":"Pätička",
"Format":"Formát",
"Format {0}":"",
"Formats":"Formáty",
"Fullscreen":"Celá obrazovka",
"G":"G",
"General":"Všeobecné",
"Gray":"Sivá",
"Green":"Zelená",
"Green component":"Zelená zložka",
"Groove":"Žliabok",
"Handy Shortcuts":"Užitočné klávesové skratky",
"Header":"Záhlavie",
"Header cell":"Bunka záhlavia",
"Heading 1":"Nadpis 1",
"Heading 2":"Nadpis 2",
"Heading 3":"Nadpis 3",
"Heading 4":"Nadpis 4",
"Heading 5":"Nadpis 5",
"Heading 6":"Nadpis 6",
"Headings":"Nadpisy",
"Height":"Výška",
"Help":"Pomocník",
"Hex color code":"HEX kód farby",
"Hidden":"Skrytý",
"Horizontal align":"Horizontálne zarovnanie",
"Horizontal line":"Horizontálna čiara",
"Horizontal space":"Horizontálny interval",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID by malo začínať písmenom, nasledované len písmenami, číslami, pomlčkami, bodkami, dvojbodkami alebo podčiarkovníkmi.",
"Image is decorative":"Obrázok je dekoratívny",
"Image list":"Zoznam obrázkov",
"Image title":"Názov obrázka",
"Image...":"Obrázok...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP chyba ImageProxy: Nepodarilo sa nájsť Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP chyba ImageProxy: Nesprávny URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP chyba ImageProxy: Odmietnutá požiadavka",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP chyba ImageProxy: Neznáma chyba ImageProxy",
"Increase indent":"Zväčšiť odsadenie",
"Inline":"Vložený",
"Insert":"Vložiť",
"Insert Template":"Vložiť šablónu",
"Insert accordion":"",
"Insert column after":"Vložiť stĺpec vpravo",
"Insert column before":"Vložiť stĺpec vľavo",
"Insert date/time":"Vložiť dátum/čas",
"Insert image":"Vložiť obrázok",
"Insert link (if link plugin activated)":"Vložiť odkaz (ak je plugin link aktivovaný)",
"Insert row after":"Vložiť riadok dole",
"Insert row before":"Vložiť riadok hore",
"Insert table":"Vložiť tabuľku",
"Insert template...":"Vložiť šablónu...",
"Insert video":"Vložiť video",
"Insert/Edit code sample":"Pridať/upraviť ukážku kódu",
"Insert/edit image":"Vložiť/upraviť obrázok",
"Insert/edit link":"Vložiť/upraviť odkaz",
"Insert/edit media":"Vložiť/upraviť médiá",
"Insert/edit video":"Vložiť/upraviť video",
"Inset":"Vložka",
"Invalid hex color code: {0}":"Neplatný HEX kód farby: {0}",
"Invalid input":"Neplatný vstup",
"Italic":"Kurzíva",
"Justify":"Zarovnať do bloku",
"Keyboard Navigation":"Navigácia klávesnicou",
"Language":"Jazyk",
"Learn more...":"Dozvedieť sa viac...",
"Left":"Vľavo",
"Left to right":"Zľava doprava",
"Light Blue":"Svetlomodrá",
"Light Gray":"Svetlosivá",
"Light Green":"Svetlozelená",
"Light Purple":"Svetlofialová",
"Light Red":"Svetločervená",
"Light Yellow":"Svetložltá",
"Line height":"Výška riadku",
"Link list":"Zoznam odkazov",
"Link...":"Odkaz...",
"List Properties":"Vlastnosti zoznamu",
"List properties...":"Vlastnosti zoznamu...",
"Loading emojis...":"Načítavanie emoji...",
"Loading...":"Načítavanie...",
"Lower Alpha":"Malé písmená",
"Lower Greek":"Malé grécke",
"Lower Roman":"Malé rímske",
"Match case":"Rozlišovať veľkosť písmen",
"Mathematical":"Matematické",
"Media poster (Image URL)":"Plagát médií (URL obrázka)",
"Media...":"Médiá...",
"Medium Blue":"Stredne modrá",
"Medium Gray":"Stredne sivá",
"Medium Purple":"Stredne fialová",
"Merge cells":"Spojiť bunky",
"Middle":"Stred",
"Midnight Blue":"Polnočná modrá",
"More...":"Viac...",
"Name":"Názov",
"Navy Blue":"Námornícka modrá",
"New document":"Nový dokument",
"New window":"Nové okno",
"Next":"Ďalej",
"No":"Nie",
"No alignment":"Bez zarovnania",
"No color":"Bez farby",
"Nonbreaking space":"Nerozdeliteľná medzera",
"None":"Žiadny",
"Numbered list":"Číslovaný zoznam",
"OR":"ALEBO",
"Objects":"Objekty",
"Ok":"OK",
"Open help dialog":"Otvoriť dialóg pomoci",
"Open link":"Otvoriť odkaz",
"Open link in...":"Otvoriť odkaz v...",
"Open popup menu for split buttons":"Otvoriť vyskakovacie menu pre rozdelené tlačidlá",
"Orange":"Oranžová",
"Outset":"Výrez",
"Page break":"Zalomenie stránky",
"Paragraph":"Odstavec",
"Paste":"Vložiť",
"Paste as text":"Vložiť ako text",
"Paste column after":"Vložiť stĺpec vpravo",
"Paste column before":"Vložiť stĺpec vľavo",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Vkladanie je teraz v režime obyčajného textu. Obsah bude vkladaný ako obyčajný text, kým túto možnosť nevypnete.",
"Paste or type a link":"Vložte alebo napíšte odkaz",
"Paste row after":"Vložiť riadok dole",
"Paste row before":"Vložiť riadok hore",
"Paste your embed code below:":"Vložte svoj vložený kód nižšie:",
"People":"Ľudia",
"Plugins":"Pluginy",
"Plugins installed ({0}):":"Nainštalované pluginy ({0}):",
"Powered by {0}":"Poháňané {0}",
"Pre":"Pre",
"Preferences":"Predvoľby",
"Preformatted":"Predformátovaný",
"Premium plugins:":"Prémiové pluginy:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Náhľad",
"Previous":"Predchádzajúci",
"Print":"Tlač",
"Print...":"Tlač...",
"Purple":"Fialová",
"Quotations":"Citácie",
"R":"R",
"Range 0 to 255":"Rozsah 0 až 255",
"Red":"Červená",
"Red component":"Červená zložka",
"Redo":"Znovu",
"Remove":"Odstrániť",
"Remove color":"Odstrániť farbu",
"Remove link":"Odstrániť odkaz",
"Replace":"Nahradiť",
"Replace all":"Nahradiť všetky",
"Replace with":"Nahradiť za",
"Resize":"Zmeniť veľkosť",
"Restore last draft":"Obnoviť posledný koncept",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Oblasť formátovaného textu",
"Rich Text Area. Press ALT-0 for help.":"Oblasť formátovaného textu. Stlačte ALT-0 pre pomoc.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Oblasť formátovaného textu. Stlačte ALT-F9 pre menu, ALT-F10 pre panel nástrojov, ALT-0 pre pomoc",
"Ridge":"Hrebeň",
"Right":"Vpravo",
"Right to left":"Zprava doľava",
"Row":"Riadok",
"Row clipboard actions":"Akcie schránky pre riadok",
"Row group":"Skupina riadkov",
"Row header":"Záhlavie riadka",
"Row properties":"Vlastnosti riadka",
"Row type":"Typ riadka",
"Rows":"Riadky",
"Save":"Uložiť",
"Save (if save plugin activated)":"Uložiť (ak je plugin save aktivovaný)",
"Scope":"Rozsah",
"Search":"Hľadať",
"Select all":"Vybrať všetky",
"Select...":"Vybrať...",
"Selection":"Výber",
"Shortcut":"Klávesová skratka",
"Show blocks":"Zobraziť bloky",
"Show caption":"Zobraziť popis",
"Show invisible characters":"Zobraziť neviditeľné znaky",
"Size":"Veľkosť",
"Solid":"Plná",
"Source":"Zdroj",
"Source code":"Zdrojový kód",
"Special Character":"Špeciálny znak",
"Special character...":"Špeciálny znak...",
"Split cell":"Rozdeliť bunku",
"Square":"Štvorec",
"Start list at number":"Začať číslovanie od",
"Strikethrough":"Prečiarknuté",
"Style":"Štýl",
"Subscript":"Dolný index",
"Superscript":"Horný index",
"Switch to or from fullscreen mode":"Prepnúť do alebo z režimu celej obrazovky",
"Symbols":"Symboly",
"System Font":"Systémové písmo",
"Table":"Tabuľka",
"Table caption":"Popis tabuľky",
"Table properties":"Vlastnosti tabuľky",
"Table styles":"Štýly tabuľky",
"Template":"Šablóna",
"Templates":"Šablóny",
"Text":"Text",
"Text color":"Farba textu",
"Text color {0}":"",
"Text to display":"Text na zobrazenie",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL, ktorý ste zadali, vyzerá ako emailová adresa. Chcete pridať požadovaný prefix mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL, ktorý ste zadali, vyzerá ako externý odkaz. Chcete pridať požadovaný prefix http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL, ktorý ste zadali, vyzerá ako externý odkaz. Chcete pridať požadovaný prefix https://?",
"Title":"Názov",
"To open the popup, press Shift+Enter":"Pre otvorenie vyskakovacieho menu stlačte Shift+Enter",
"Toggle accordion":"",
"Tools":"Nástroje",
"Top":"Hore",
"Travel and Places":"Cestovanie a miesta",
"Turquoise":"Tyrkysová",
"Underline":"Podčiarknuté",
"Undo":"Späť",
"Upload":"Nahrať",
"Uploading image":"Nahrávanie obrázka",
"Upper Alpha":"Veľké písmená",
"Upper Roman":"Veľké rímske",
"Url":"URL",
"User Defined":"Definované používateľom",
"Valid":"Platný",
"Version":"Verzia",
"Vertical align":"Vertikálne zarovnanie",
"Vertical space":"Vertikálny interval",
"View":"Zobrazenie",
"Visual aids":"Vizuálne pomôcky",
"Warn":"Varovanie",
"White":"Biela",
"Width":"Šírka",
"Word count":"Počet slov",
"Words":"Slová",
"Words: {0}":"Slová: {0}",
"Yellow":"Žltá",
"Yes":"Áno",
"You are using {0}":"Používate {0}",
"You have unsaved changes are you sure you want to navigate away?":"Máte neuložené zmeny. Ste si istí, že chcete odísť?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Váš prehliadač nepodporuje priamy prístup k schránke. Namiesto toho použite klávesové skratky Ctrl+X/C/V.",
"alignment":"zarovnanie",
"austral sign":"znak austral",
"cedi sign":"znak cedi",
"colon sign":"dvojbodka",
"cruzeiro sign":"znak cruzeiro",
"currency sign":"znak meny",
"dollar sign":"znak dolára",
"dong sign":"znak dong",
"drachma sign":"znak drachmy",
"euro-currency sign":"znak eura",
"example":"príklad",
"formatting":"formátovanie",
"french franc sign":"znak francúzskeho franku",
"german penny symbol":"znak nemeckého fenigu",
"guarani sign":"znak guarani",
"history":"história",
"hryvnia sign":"znak hryvne",
"indentation":"odsadenie",
"indian rupee sign":"znak indickej rupie",
"kip sign":"znak kip",
"lira sign":"znak líry",
"livre tournois sign":"znak livre tournois",
"manat sign":"znak manatu",
"mill sign":"znak mil",
"naira sign":"znak naira",
"new sheqel sign":"znak nového šekelu",
"nordic mark sign":"znak nordickej marky",
"peseta sign":"znak pesety",
"peso sign":"znak pesa",
"ruble sign":"znak rubľa",
"rupee sign":"znak rupie",
"spesmilo sign":"znak spesmilo",
"styles":"štýly",
"tenge sign":"znak tenge",
"tugrik sign":"znak tugrika",
"turkish lira sign":"znak tureckej líry",
"won sign":"znak wonu",
"yen character":"znak jenu",
"yen/yuan character variant one":"znak jenu/juana, variant 1",
"yuan character":"znak juana",
"yuan character, in hong kong and taiwan":"znak juana, Hongkong a Taiwan",
"{0} characters":"{0} znakov",
"{0} columns, {1} rows":"",
"{0} words":"{0} slov"
});
