tinymce.addI18n("sl",{
"#":"#",
"Accessibility":"Dostopnost",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Dejanje",
"Activity":"Aktivnost",
"Address":"Naslov",
"Advanced":"Napredno",
"Align":"Poravnaj",
"Align center":"Centriraj",
"Align left":"Poravnaj levo",
"Align right":"Poravnaj desno",
"Alignment":"Poravnanje",
"Alignment {0}":"",
"All":"Vse",
"Alternative description":"Alternativni opis",
"Alternative source":"Alternativni vir",
"Alternative source URL":"URL alternativnega vira",
"Anchor":"Sidro",
"Anchor...":"Sidro...",
"Anchors":"Sidra",
"Animals and Nature":"Živali in narava",
"Arrows":"Puščice",
"B":"B",
"Background color":"Barva ozadja",
"Background color {0}":"",
"Black":"Črna",
"Block":"Blok",
"Block {0}":"",
"Blockquote":"Blok citat",
"Blocks":"Bloki",
"Blue":"Modra",
"Blue component":"Modra komponenta",
"Body":"Telo",
"Bold":"Krepko",
"Border":"Obroba",
"Border color":"Barva obrobe",
"Border style":"Slog obrobe",
"Border width":"Širina obrobe",
"Bottom":"Spodaj",
"Browse files":"",
"Browse for an image":"Prebrskaj slike",
"Browse links":"",
"Bullet list":"Seznam z oznakami",
"Cancel":"Prekliči",
"Caption":"Naslov",
"Cell":"Celica",
"Cell padding":"Notranji odmik celice",
"Cell properties":"Lastnosti celice",
"Cell spacing":"Zunanji odmik celice",
"Cell styles":"Slogi celice",
"Cell type":"Tip celice",
"Center":"Sredina",
"Characters":"Znaki",
"Characters (no spaces)":"Znaki (brez presledkov)",
"Circle":"Krog",
"Class":"Razred",
"Clear formatting":"Počisti oblikovanje",
"Close":"Zapri",
"Code":"Koda",
"Code sample...":"Primer kode...",
"Code view":"Pogled kode",
"Color Picker":"Izbira barve",
"Color swatch":"Vzorec barve",
"Cols":"Stolpci",
"Column":"Stolpec",
"Column clipboard actions":"Dejanja odložišča za stolpec",
"Column group":"Skupina stolpcev",
"Column header":"Glava stolpca",
"Constrain proportions":"Omeji proporce",
"Copy":"Kopiraj",
"Copy column":"Kopiraj stolpec",
"Copy row":"Kopiraj vrstico",
"Could not find the specified string.":"Ni mogoče najti navedenega niza.",
"Could not load emojis":"Ni mogoče naložiti emojijev",
"Count":"Število",
"Currency":"Valuta",
"Current window":"Trenutno okno",
"Custom color":"Prilagojena barva",
"Custom...":"Prilagojeno...",
"Cut":"Izreži",
"Cut column":"Izreži stolpec",
"Cut row":"Izreži vrstico",
"Dark Blue":"Temno modra",
"Dark Gray":"Temno siva",
"Dark Green":"Temno zelena",
"Dark Orange":"Temno oranžna",
"Dark Purple":"Temno vijolična",
"Dark Red":"Temno rdeča",
"Dark Turquoise":"Temno turkizna",
"Dark Yellow":"Temno rumena",
"Dashed":"Črtkana",
"Date/time":"Datum/čas",
"Decrease indent":"Zmanjšaj zamik",
"Default":"Privzeto",
"Delete accordion":"",
"Delete column":"Izbriši stolpec",
"Delete row":"Izbriši vrstico",
"Delete table":"Izbriši tabelo",
"Dimensions":"Dimenzije",
"Disc":"Disk",
"Div":"Div",
"Document":"Dokument",
"Dotted":"Pikčasta",
"Double":"Dvojna",
"Drop an image here":"Spusti sliko tukaj",
"Dropped file type is not supported":"Tip datoteke ni podprt",
"Edit":"Uredi",
"Embed":"Vgrajeno",
"Emojis":"Emojiji",
"Emojis...":"Emojiji...",
"Error":"Napaka",
"Error: Form submit field collision.":"Napaka: Trk polj za pošiljanje obrazca.",
"Error: No form element found.":"Napaka: Element obrazca ni najden.",
"Extended Latin":"Razširjena latinica",
"Failed to initialize plugin: {0}":"Neuspešna inicializacija vtičnika: {0}",
"Failed to load plugin url: {0}":"Neuspešno nalaganje URL vtičnika: {0}",
"Failed to load plugin: {0} from url {1}":"Neuspešno nalaganje vtičnika: {0} iz URL {1}",
"Failed to upload image: {0}":"Neuspešno nalaganje slike: {0}",
"File":"Datoteka",
"Find":"Najdi",
"Find (if searchreplace plugin activated)":"Najdi (če je vtičnik searchreplace aktiviran)",
"Find and Replace":"Najdi in zamenjaj",
"Find and replace...":"Najdi in zamenjaj...",
"Find in selection":"Išči v izbiri",
"Find whole words only":"Najdi samo cele besede",
"Flags":"Zastave",
"Focus to contextual toolbar":"Fokus na kontekstno orodno vrstico",
"Focus to element path":"Fokus na pot elementa",
"Focus to menubar":"Fokus na menijsko vrstico",
"Focus to toolbar":"Fokus na orodno vrstico",
"Font":"Pisava",
"Font size {0}":"",
"Font sizes":"Velikosti pisave",
"Font {0}":"",
"Fonts":"Pisave",
"Food and Drink":"Hrana in pijača",
"Footer":"Noga",
"Format":"Format",
"Format {0}":"",
"Formats":"Formati",
"Fullscreen":"Celoten zaslon",
"G":"G",
"General":"Splošno",
"Gray":"Siva",
"Green":"Zelena",
"Green component":"Zelena komponenta",
"Groove":"Žleb",
"Handy Shortcuts":"Uporabne bližnjice",
"Header":"Glava",
"Header cell":"Celica glave",
"Heading 1":"Naslov 1",
"Heading 2":"Naslov 2",
"Heading 3":"Naslov 3",
"Heading 4":"Naslov 4",
"Heading 5":"Naslov 5",
"Heading 6":"Naslov 6",
"Headings":"Naslovi",
"Height":"Višina",
"Help":"Pomoč",
"Hex color code":"HEX koda barve",
"Hidden":"Skrito",
"Horizontal align":"Horizontalno poravnanje",
"Horizontal line":"Horizontalna črta",
"Horizontal space":"Horizontalni prostor",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID naj se začne s črko, ki ji sledijo samo črke, številke, pomišljaji, pike, dvopičja ali podčrtaji.",
"Image is decorative":"Slika je dekorativna",
"Image list":"Seznam slik",
"Image title":"Naslov slike",
"Image...":"Slika...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP napaka ImageProxy: Ni mogoče najti Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP napaka ImageProxy: Napačen URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP napaka ImageProxy: Zavrnjena zahteva",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP napaka ImageProxy: Neznana napaka ImageProxy",
"Increase indent":"Povečaj zamik",
"Inline":"Vgrajeno",
"Insert":"Vstavi",
"Insert Template":"Vstavi predlogo",
"Insert accordion":"",
"Insert column after":"Vstavi stolpec desno",
"Insert column before":"Vstavi stolpec levo",
"Insert date/time":"Vstavi datum/čas",
"Insert image":"Vstavi sliko",
"Insert link (if link plugin activated)":"Vstavi povezavo (če je vtičnik link aktiviran)",
"Insert row after":"Vstavi vrstico spodaj",
"Insert row before":"Vstavi vrstico zgoraj",
"Insert table":"Vstavi tabelo",
"Insert template...":"Vstavi predlogo...",
"Insert video":"Vstavi video",
"Insert/Edit code sample":"Dodaj/Uredi primer kode",
"Insert/edit image":"Vstavi/uredi sliko",
"Insert/edit link":"Vstavi/uredi povezavo",
"Insert/edit media":"Vstavi/uredi medije",
"Insert/edit video":"Vstavi/uredi video",
"Inset":"Vložek",
"Invalid hex color code: {0}":"Neveljavna HEX koda barve: {0}",
"Invalid input":"Neveljaven vnos",
"Italic":"Ležeče",
"Justify":"Poravnaj po širini",
"Keyboard Navigation":"Navigacija s tipkovnico",
"Language":"Jezik",
"Learn more...":"Izvedi več...",
"Left":"Levo",
"Left to right":"Od leve proti desni",
"Light Blue":"Svetlo modra",
"Light Gray":"Svetlo siva",
"Light Green":"Svetlo zelena",
"Light Purple":"Svetlo vijolična",
"Light Red":"Svetlo rdeča",
"Light Yellow":"Svetlo rumena",
"Line height":"Višina vrstice",
"Link list":"Seznam povezav",
"Link...":"Povezava...",
"List Properties":"Lastnosti seznama",
"List properties...":"Lastnosti seznama...",
"Loading emojis...":"Nalaganje emojijev...",
"Loading...":"Nalaganje...",
"Lower Alpha":"Male črke",
"Lower Greek":"Male grške",
"Lower Roman":"Male rimske",
"Match case":"Ujemanje velikosti črk",
"Mathematical":"Matematično",
"Media poster (Image URL)":"Plakat medijev (URL slike)",
"Media...":"Mediji...",
"Medium Blue":"Srednje modra",
"Medium Gray":"Srednje siva",
"Medium Purple":"Srednje vijolična",
"Merge cells":"Združi celice",
"Middle":"Sredina",
"Midnight Blue":"Polnočno modra",
"More...":"Več...",
"Name":"Ime",
"Navy Blue":"Mornarsko modra",
"New document":"Nov dokument",
"New window":"Novo okno",
"Next":"Naprej",
"No":"Ne",
"No alignment":"Brez poravnave",
"No color":"Brez barve",
"Nonbreaking space":"Nerazdeljiv presledek",
"None":"Noben",
"Numbered list":"Oštevilčen seznam",
"OR":"ALI",
"Objects":"Predmeti",
"Ok":"OK",
"Open help dialog":"Odpri dialog pomoči",
"Open link":"Odpri povezavo",
"Open link in...":"Odpri povezavo v...",
"Open popup menu for split buttons":"Odpri pojavno meni za razdeljene gumbove",
"Orange":"Oranžna",
"Outset":"Izrez",
"Page break":"Prelom strani",
"Paragraph":"Odstavek",
"Paste":"Prilepi",
"Paste as text":"Prilepi kot besedilo",
"Paste column after":"Prilepi stolpec desno",
"Paste column before":"Prilepi stolpec levo",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Lepljenje je zdaj v načinu navadnega besedila. Vsebina bo prilepljena kot navadno besedilo, dokler te možnosti ne izključite.",
"Paste or type a link":"Prilepite ali vnesite povezavo",
"Paste row after":"Prilepi vrstico spodaj",
"Paste row before":"Prilepi vrstico zgoraj",
"Paste your embed code below:":"Prilepite svojo vgrajeno kodo spodaj:",
"People":"Ljudje",
"Plugins":"Vtičniki",
"Plugins installed ({0}):":"Nameščeni vtičniki ({0}):",
"Powered by {0}":"Poganja {0}",
"Pre":"Pre",
"Preferences":"Nastavitve",
"Preformatted":"Predhodno oblikovan",
"Premium plugins:":"Premium vtičniki:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Predogled",
"Previous":"Prejšnji",
"Print":"Natisni",
"Print...":"Natisni...",
"Purple":"Vijolična",
"Quotations":"Citat",
"R":"R",
"Range 0 to 255":"Obseg 0 do 255",
"Red":"Rdeča",
"Red component":"Rdeča komponenta",
"Redo":"Ponovi",
"Remove":"Odstrani",
"Remove color":"Odstrani barvo",
"Remove link":"Odstrani povezavo",
"Replace":"Zamenjaj",
"Replace all":"Zamenjaj vse",
"Replace with":"Zamenjaj z",
"Resize":"Spremeni velikost",
"Restore last draft":"Obnovi zadnji osnutek",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Območje obogatenega besedila",
"Rich Text Area. Press ALT-0 for help.":"Območje obogatenega besedila. Pritisnite ALT-0 za pomoč.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Območje obogatenega besedila. Pritisnite ALT-F9 za meni, ALT-F10 za orodno vrstico, ALT-0 za pomoč",
"Ridge":"Greben",
"Right":"Desno",
"Right to left":"Od desne proti levi",
"Row":"Vrstica",
"Row clipboard actions":"Dejanja odložišča za vrstico",
"Row group":"Skupina vrstic",
"Row header":"Glava vrstice",
"Row properties":"Lastnosti vrstice",
"Row type":"Tip vrstice",
"Rows":"Vrstice",
"Save":"Shrani",
"Save (if save plugin activated)":"Shrani (če je vtičnik save aktiviran)",
"Scope":"Obseg",
"Search":"Išči",
"Select all":"Izberi vse",
"Select...":"Izberi...",
"Selection":"Izbira",
"Shortcut":"Bližnjica",
"Show blocks":"Prikaži bloke",
"Show caption":"Prikaži naslov",
"Show invisible characters":"Prikaži nevidne znake",
"Size":"Velikost",
"Solid":"Polna",
"Source":"Vir",
"Source code":"Izvorna koda",
"Special Character":"Poseben znak",
"Special character...":"Poseben znak...",
"Split cell":"Razdeli celico",
"Square":"Kvadrat",
"Start list at number":"Začni številčenje od",
"Strikethrough":"Prečrtano",
"Style":"Slog",
"Subscript":"Podpisano",
"Superscript":"Nadpisano",
"Switch to or from fullscreen mode":"Preklopi v ali iz načina celotnega zaslona",
"Symbols":"Simboli",
"System Font":"Sistemska pisava",
"Table":"Tabela",
"Table caption":"Naslov tabele",
"Table properties":"Lastnosti tabele",
"Table styles":"Slogi tabele",
"Template":"Predloga",
"Templates":"Predloge",
"Text":"Besedilo",
"Text color":"Barva besedila",
"Text color {0}":"",
"Text to display":"Besedilo za prikaz",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL, ki ste vnesli, se zdi kot e-poštni naslov. Ali želite dodati potrebni predponi mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL, ki ste vnesli, se zdi kot zunanja povezava. Ali želite dodati potrebni predponi http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL, ki ste vnesli, se zdi kot zunanja povezava. Ali želite dodati potrebni predponi https://?",
"Title":"Naslov",
"To open the popup, press Shift+Enter":"Za odpiranje pojavnega menija pritisnite Shift+Enter",
"Toggle accordion":"",
"Tools":"Orodja",
"Top":"Zgoraj",
"Travel and Places":"Potovanja in kraji",
"Turquoise":"Turkizna",
"Underline":"Podčrtano",
"Undo":"Razveljavi",
"Upload":"Naloži",
"Uploading image":"Nalaganje slike",
"Upper Alpha":"Velike črke",
"Upper Roman":"Velike rimske",
"Url":"URL",
"User Defined":"Uporabniško definirano",
"Valid":"Veljavno",
"Version":"Verzija",
"Vertical align":"Vertikalno poravnanje",
"Vertical space":"Vertikalni prostor",
"View":"Pogled",
"Visual aids":"Vizualne pomoči",
"Warn":"Opozorilo",
"White":"Bela",
"Width":"Širina",
"Word count":"Število besed",
"Words":"Besede",
"Words: {0}":"Besede: {0}",
"Yellow":"Rumena",
"Yes":"Da",
"You are using {0}":"Uporabljate {0}",
"You have unsaved changes are you sure you want to navigate away?":"Imate neshranjene spremembe. Ali ste prepričani, da se želite oditi?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Vaš brskalnik ne podpira neposrednega dostopa do odložišča. Namesto tega uporabite bližnjice tipkovnice Ctrl+X/C/V.",
"alignment":"poravnanje",
"austral sign":"znak austral",
"cedi sign":"znak cedi",
"colon sign":"dvopičje",
"cruzeiro sign":"znak cruzeiro",
"currency sign":"znak valute",
"dollar sign":"znak dolarja",
"dong sign":"znak dong",
"drachma sign":"znak drahme",
"euro-currency sign":"znak evra",
"example":"primer",
"formatting":"oblikovanje",
"french franc sign":"znak francoskega franka",
"german penny symbol":"znak nemškega penija",
"guarani sign":"znak guarani",
"history":"zgodovina",
"hryvnia sign":"znak grivne",
"indentation":"zamik",
"indian rupee sign":"znak indijske rupije",
"kip sign":"znak kip",
"lira sign":"znak lire",
"livre tournois sign":"znak livre tournois",
"manat sign":"znak manata",
"mill sign":"znak mil",
"naira sign":"znak naira",
"new sheqel sign":"znak novega šekla",
"nordic mark sign":"znak nordijske marke",
"peseta sign":"znak pesete",
"peso sign":"znak pesa",
"ruble sign":"znak rublja",
"rupee sign":"znak rupije",
"spesmilo sign":"znak spesmilo",
"styles":"slogi",
"tenge sign":"znak tenge",
"tugrik sign":"znak tugrika",
"turkish lira sign":"znak turške lire",
"won sign":"znak wona",
"yen character":"znak jene",
"yen/yuan character variant one":"znak jene/juana, varianta 1",
"yuan character":"znak juana",
"yuan character, in hong kong and taiwan":"znak juana, Hong Kong in Tajvan",
"{0} characters":"{0} znakov",
"{0} columns, {1} rows":"",
"{0} words":"{0} besed"
});
