tinymce.addI18n("sr",{
"#":"#",
"Accessibility":"Приступачност",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Акција",
"Activity":"Активност",
"Address":"Адреса",
"Advanced":"Напредно",
"Align":"Поравнај",
"Align center":"Центрирај",
"Align left":"Поравнај лево",
"Align right":"Поравнај десно",
"Alignment":"Поравнавање",
"Alignment {0}":"",
"All":"Све",
"Alternative description":"Алтернативни опис",
"Alternative source":"Алтернативни извор",
"Alternative source URL":"URL алтернативног извора",
"Anchor":"Сидро",
"Anchor...":"Сидро...",
"Anchors":"Сидриња",
"Animals and Nature":"Животиње и природа",
"Arrows":"Стрелице",
"B":"B",
"Background color":"Боја позадине",
"Background color {0}":"",
"Black":"Црна",
"Block":"Блок",
"Block {0}":"",
"Blockquote":"Блок цитат",
"Blocks":"Блокови",
"Blue":"Плава",
"Blue component":"Плава компонента",
"Body":"Тело",
"Bold":"Подебљано",
"Border":"Граница",
"Border color":"Боја границе",
"Border style":"Стил границе",
"Border width":"Ширина границе",
"Bottom":"Доле",
"Browse files":"",
"Browse for an image":"Претражи слике",
"Browse links":"",
"Bullet list":"Листа са тачкама",
"Cancel":"Откажи",
"Caption":"Наслов",
"Cell":"Ћелија",
"Cell padding":"Унутрашњи размак ћелије",
"Cell properties":"Својства ћелије",
"Cell spacing":"Спољашњи размак ћелије",
"Cell styles":"Стилови ћелије",
"Cell type":"Тип ћелије",
"Center":"Центар",
"Characters":"Знакови",
"Characters (no spaces)":"Знакови (без размака)",
"Circle":"Круг",
"Class":"Класа",
"Clear formatting":"Очисти форматирање",
"Close":"Затвори",
"Code":"Код",
"Code sample...":"Пример кода...",
"Code view":"Приказ кода",
"Color Picker":"Бирач боја",
"Color swatch":"Узорак боје",
"Cols":"Колоне",
"Column":"Колона",
"Column clipboard actions":"Акције међуспремника за колону",
"Column group":"Група колона",
"Column header":"Заглавље колоне",
"Constrain proportions":"Ограничи пропорције",
"Copy":"Копирај",
"Copy column":"Копирај колону",
"Copy row":"Копирај ред",
"Could not find the specified string.":"Није могуће пронаћи наведени низ.",
"Could not load emojis":"Није могуће учитати емоције",
"Count":"Број",
"Currency":"Валута",
"Current window":"Тренутни прозор",
"Custom color":"Прилагођена боја",
"Custom...":"Прилагођено...",
"Cut":"Исеци",
"Cut column":"Исеци колону",
"Cut row":"Исеци ред",
"Dark Blue":"Тамноплава",
"Dark Gray":"Тамносива",
"Dark Green":"Тамнозелена",
"Dark Orange":"Тамно наранџаста",
"Dark Purple":"Тамнољубичаста",
"Dark Red":"Тамноцрвена",
"Dark Turquoise":"Тамно тиркизна",
"Dark Yellow":"Тамножута",
"Dashed":"Испрекидана",
"Date/time":"Датум/време",
"Decrease indent":"Смањи увлачење",
"Default":"Подразумевано",
"Delete accordion":"",
"Delete column":"Обриши колону",
"Delete row":"Обриши ред",
"Delete table":"Обриши табелу",
"Dimensions":"Димензије",
"Disc":"Диск",
"Div":"Div",
"Document":"Документ",
"Dotted":"Тачкаста",
"Double":"Двострука",
"Drop an image here":"Овде испусти слику",
"Dropped file type is not supported":"Тип датотеке није подржан",
"Edit":"Уреди",
"Embed":"Уграђено",
"Emojis":"Емоције",
"Emojis...":"Емоције...",
"Error":"Грешка",
"Error: Form submit field collision.":"Грешка: Судар поља за слање форме.",
"Error: No form element found.":"Грешка: Елемент форме није пронађен.",
"Extended Latin":"Проширена латиница",
"Failed to initialize plugin: {0}":"Неуспешна иницијализација прикључка: {0}",
"Failed to load plugin url: {0}":"Неуспешно учитавање URL прикључка: {0}",
"Failed to load plugin: {0} from url {1}":"Неуспешно учитавање прикључка: {0} из URL {1}",
"Failed to upload image: {0}":"Неуспешно учитавање слике: {0}",
"File":"Датотека",
"Find":"Пронађи",
"Find (if searchreplace plugin activated)":"Пронађи (ако је прикључак searchreplace активиран)",
"Find and Replace":"Пронађи и замени",
"Find and replace...":"Пронађи и замени...",
"Find in selection":"Тражи у избору",
"Find whole words only":"Пронађи само целе речи",
"Flags":"Заставе",
"Focus to contextual toolbar":"Фокус на контекстуалну траку алата",
"Focus to element path":"Фокус на пут елемента",
"Focus to menubar":"Фокус на траку менија",
"Focus to toolbar":"Фокус на траку алата",
"Font":"Фонт",
"Font size {0}":"",
"Font sizes":"Величине фонта",
"Font {0}":"",
"Fonts":"Фонтови",
"Food and Drink":"Храна и пиће",
"Footer":"Подножје",
"Format":"Формат",
"Format {0}":"",
"Formats":"Формати",
"Fullscreen":"Пун екран",
"G":"G",
"General":"Опште",
"Gray":"Сива",
"Green":"Зелена",
"Green component":"Зелена компонента",
"Groove":"Жлеб",
"Handy Shortcuts":"Корисни пречице",
"Header":"Заглавље",
"Header cell":"Ћелија заглавља",
"Heading 1":"Наслов 1",
"Heading 2":"Наслов 2",
"Heading 3":"Наслов 3",
"Heading 4":"Наслов 4",
"Heading 5":"Наслов 5",
"Heading 6":"Наслов 6",
"Headings":"Наслови",
"Height":"Висина",
"Help":"Помоћ",
"Hex color code":"HEX код боје",
"Hidden":"Скривено",
"Horizontal align":"Хоризонтално поравнавање",
"Horizontal line":"Хоризонтална линија",
"Horizontal space":"Хоризонтални размак",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID треба да почне словом, праћеним само словима, бројевима, цртицама, тачкама, двотачкама или подвлакама.",
"Image is decorative":"Слика је декоративна",
"Image list":"Листа слика",
"Image title":"Наслов слике",
"Image...":"Слика...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP грешка ImageProxy: Није могуће пронаћи Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP грешка ImageProxy: Нетачан URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP грешка ImageProxy: Одбијен захтев",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP грешка ImageProxy: Непозната грешка ImageProxy",
"Increase indent":"Повећај увлачење",
"Inline":"Уграђено",
"Insert":"Уметни",
"Insert Template":"Уметни шаблон",
"Insert accordion":"",
"Insert column after":"Уметни колону десно",
"Insert column before":"Уметни колону лево",
"Insert date/time":"Уметни датум/време",
"Insert image":"Уметни слику",
"Insert link (if link plugin activated)":"Уметни везу (ако је прикључак link активиран)",
"Insert row after":"Уметни ред доле",
"Insert row before":"Уметни ред горе",
"Insert table":"Уметни табелу",
"Insert template...":"Уметни шаблон...",
"Insert video":"Уметни видео",
"Insert/Edit code sample":"Додај/Уреди пример кода",
"Insert/edit image":"Уметни/уреди слику",
"Insert/edit link":"Уметни/уреди везу",
"Insert/edit media":"Уметни/уреди медије",
"Insert/edit video":"Уметни/уреди видео",
"Inset":"Уметак",
"Invalid hex color code: {0}":"Неважећи HEX код боје: {0}",
"Invalid input":"Неважећи унос",
"Italic":"Курзив",
"Justify":"Поравнај по ширини",
"Keyboard Navigation":"Навигација тастатуром",
"Language":"Језик",
"Learn more...":"Сазнај више...",
"Left":"Лево",
"Left to right":"С лева на десно",
"Light Blue":"Светлоплава",
"Light Gray":"Светлосива",
"Light Green":"Светлозелена",
"Light Purple":"Светлољубичаста",
"Light Red":"Светлоцрвена",
"Light Yellow":"Светложута",
"Line height":"Висина линије",
"Link list":"Листа веза",
"Link...":"Веза...",
"List Properties":"Својства листе",
"List properties...":"Својства листе...",
"Loading emojis...":"Учитавање емоција...",
"Loading...":"Учитавање...",
"Lower Alpha":"Мала слова",
"Lower Greek":"Мали грчки",
"Lower Roman":"Мали римски",
"Match case":"Упореди велика/мала слова",
"Mathematical":"Математички",
"Media poster (Image URL)":"Постер медија (URL слике)",
"Media...":"Медији...",
"Medium Blue":"Средње плава",
"Medium Gray":"Средње сива",
"Medium Purple":"Средње љубичаста",
"Merge cells":"Споји ћелије",
"Middle":"Средина",
"Midnight Blue":"Понокћно плава",
"More...":"Више...",
"Name":"Име",
"Navy Blue":"Морнарско плава",
"New document":"Нови документ",
"New window":"Нови прозор",
"Next":"Следеће",
"No":"Не",
"No alignment":"Без поравнавања",
"No color":"Без боје",
"Nonbreaking space":"Нераскидљиви размак",
"None":"Ниједан",
"Numbered list":"Нумерисана листа",
"OR":"ИЛИ",
"Objects":"Објекти",
"Ok":"OK",
"Open help dialog":"Отвори дијалог помоћи",
"Open link":"Отвори везу",
"Open link in...":"Отвори везу у...",
"Open popup menu for split buttons":"Отвори popup мени за подељене дугмад",
"Orange":"Наранџаста",
"Outset":"Изрезка",
"Page break":"Прелом странице",
"Paragraph":"Параграф",
"Paste":"Залепи",
"Paste as text":"Залепи као текст",
"Paste column after":"Залепи колону десно",
"Paste column before":"Залепи колону лево",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Лепљење је сада у режиму обичног текста. Садржај ће се лепити као обичан текст док не искључите ову опцију.",
"Paste or type a link":"Залепите или унесите везу",
"Paste row after":"Залепи ред доле",
"Paste row before":"Залепи ред горе",
"Paste your embed code below:":"Залепите свој уграђени код испод:",
"People":"Људи",
"Plugins":"Прикључци",
"Plugins installed ({0}):":"Инсталирани прикључци ({0}):",
"Powered by {0}":"Покреће {0}",
"Pre":"Pre",
"Preferences":"Подешавања",
"Preformatted":"Унапред форматиран",
"Premium plugins:":"Премијум прикључци:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Преглед",
"Previous":"Претходно",
"Print":"Штампај",
"Print...":"Штампај...",
"Purple":"Љубичаста",
"Quotations":"Цитати",
"R":"R",
"Range 0 to 255":"Опсег од 0 до 255",
"Red":"Црвена",
"Red component":"Црвена компонента",
"Redo":"Понови",
"Remove":"Уклони",
"Remove color":"Уклони боју",
"Remove link":"Уклони везу",
"Replace":"Замени",
"Replace all":"Замени све",
"Replace with":"Замени са",
"Resize":"Промени величину",
"Restore last draft":"Врати последњи нацрт",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Област обогаћеног текста",
"Rich Text Area. Press ALT-0 for help.":"Област обогаћеног текста. Притисните ALT-0 за помоћ.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Област обогаћеног текста. Притисните ALT-F9 за мени, ALT-F10 за траку алата, ALT-0 за помоћ",
"Ridge":"Гребен",
"Right":"Десно",
"Right to left":"С десна на лево",
"Row":"Ред",
"Row clipboard actions":"Акције међуспремника за ред",
"Row group":"Група редова",
"Row header":"Заглавље реда",
"Row properties":"Својства реда",
"Row type":"Тип реда",
"Rows":"Редови",
"Save":"Сачувај",
"Save (if save plugin activated)":"Сачувај (ако је прикључак save активиран)",
"Scope":"Опсег",
"Search":"Претражи",
"Select all":"Изабери све",
"Select...":"Изабери...",
"Selection":"Избор",
"Shortcut":"Пречица",
"Show blocks":"Прикажи блокове",
"Show caption":"Прикажи наслов",
"Show invisible characters":"Прикажи невидљиве знакове",
"Size":"Величина",
"Solid":"Пуна",
"Source":"Извор",
"Source code":"Изворни код",
"Special Character":"Посебан знак",
"Special character...":"Посебан знак...",
"Split cell":"Подели ћелију",
"Square":"Квадрат",
"Start list at number":"Почни нумерацију од",
"Strikethrough":"Прецртано",
"Style":"Стил",
"Subscript":"Индекс",
"Superscript":"Експонент",
"Switch to or from fullscreen mode":"Пребаци у или из режима пуног екрана",
"Symbols":"Симболи",
"System Font":"Системски фонт",
"Table":"Табела",
"Table caption":"Наслов табеле",
"Table properties":"Својства табеле",
"Table styles":"Стилови табеле",
"Template":"Шаблон",
"Templates":"Шаблони",
"Text":"Текст",
"Text color":"Боја текста",
"Text color {0}":"",
"Text to display":"Текст за приказ",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL који сте унели изгледа као е-маил адреса. Да ли желите да додате потребни префикс mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL који сте унели изгледа као спољна веза. Да ли желите да додате потребни префикс http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL који сте унели изгледа као спољна веза. Да ли желите да додате потребни префикс https://?",
"Title":"Наслов",
"To open the popup, press Shift+Enter":"За отварање popup менија притисните Shift+Enter",
"Toggle accordion":"",
"Tools":"Алати",
"Top":"Горе",
"Travel and Places":"Путовања и места",
"Turquoise":"Тиркизна",
"Underline":"Подвучено",
"Undo":"Поништи",
"Upload":"Учитај",
"Uploading image":"Учитавање слике",
"Upper Alpha":"Велика слова",
"Upper Roman":"Велики римски",
"Url":"URL",
"User Defined":"Дефинисано од стране корисника",
"Valid":"Важећи",
"Version":"Верзија",
"Vertical align":"Вертикално поравнавање",
"Vertical space":"Вертикални размак",
"View":"Приказ",
"Visual aids":"Визуелне помоћи",
"Warn":"Упозорење",
"White":"Бела",
"Width":"Ширина",
"Word count":"Број речи",
"Words":"Речи",
"Words: {0}":"Речи: {0}",
"Yellow":"Жута",
"Yes":"Да",
"You are using {0}":"Користите {0}",
"You have unsaved changes are you sure you want to navigate away?":"Имате несачуване промене. Да ли сте сигурни да желите да одете?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Ваш прегледач не подржава директан приступ међуспремнику. Молимо користите Ctrl+X/C/V пречице тастатуре.",
"alignment":"поравнавање",
"austral sign":"знак аустрал",
"cedi sign":"знак цеди",
"colon sign":"двотачка",
"cruzeiro sign":"знак крузеиро",
"currency sign":"знак валуте",
"dollar sign":"знак долара",
"dong sign":"знак донг",
"drachma sign":"знак драхме",
"euro-currency sign":"знак евра",
"example":"пример",
"formatting":"форматирање",
"french franc sign":"знак француског франка",
"german penny symbol":"знак немачког пенија",
"guarani sign":"знак гуарани",
"history":"историја",
"hryvnia sign":"знак гривне",
"indentation":"увлачење",
"indian rupee sign":"знак индијске рупије",
"kip sign":"знак кип",
"lira sign":"знак лире",
"livre tournois sign":"знак ливре",
"manat sign":"знак маната",
"mill sign":"знак мил",
"naira sign":"знак наира",
"new sheqel sign":"знак новог шекела",
"nordic mark sign":"знак нордичке марке",
"peseta sign":"знак песете",
"peso sign":"знак песа",
"ruble sign":"знак рубље",
"rupee sign":"знак рупије",
"spesmilo sign":"знак спесмило",
"styles":"стилови",
"tenge sign":"знак тенге",
"tugrik sign":"знак тугрика",
"turkish lira sign":"знак турске лире",
"won sign":"знак вона",
"yen character":"знак јена",
"yen/yuan character variant one":"знак јена/јуана, варијанта 1",
"yuan character":"знак јуана",
"yuan character, in hong kong and taiwan":"знак јуана, Хонг Конг и Тајван",
"{0} characters":"{0} знакова",
"{0} columns, {1} rows":"",
"{0} words":"{0} речи"
});
