tinymce.addI18n("ua",{
"#":"#",
"Accessibility":"Доступність",
"Accordion":"",
"Accordion body...":"",
"Accordion summary...":"",
"Action":"Дія",
"Activity":"Активність",
"Address":"Адреса",
"Advanced":"Розширені",
"Align":"Вирівняти",
"Align center":"Вирівняти по центру",
"Align left":"Вирівняти по лівому краю",
"Align right":"Вирівняти по правому краю",
"Alignment":"Вирівнювання",
"Alignment {0}":"",
"All":"Всі",
"Alternative description":"Альтернативний опис",
"Alternative source":"Альтернативне джерело",
"Alternative source URL":"URL альтернативного джерела",
"Anchor":"Якір",
"Anchor...":"Якір...",
"Anchors":"Якорі",
"Animals and Nature":"Тварини та природа",
"Arrows":"Стрілки",
"B":"B",
"Background color":"Колір фону",
"Background color {0}":"",
"Black":"Чорний",
"Block":"Блок",
"Block {0}":"",
"Blockquote":"Блок цитати",
"Blocks":"Блоки",
"Blue":"Синій",
"Blue component":"Синя компонента",
"Body":"Тіло",
"Bold":"Жирний",
"Border":"Рамка",
"Border color":"Колір рамки",
"Border style":"Стиль рамки",
"Border width":"Ширина рамки",
"Bottom":"Знизу",
"Browse files":"",
"Browse for an image":"Переглянути зображення",
"Browse links":"",
"Bullet list":"Маркований список",
"Cancel":"Скасувати",
"Caption":"Підпис",
"Cell":"Клітинка",
"Cell padding":"Внутрішній відступ клітинки",
"Cell properties":"Властивості клітинки",
"Cell spacing":"Зовнішній відступ клітинки",
"Cell styles":"Стилі клітинки",
"Cell type":"Тип клітинки",
"Center":"Центр",
"Characters":"Символи",
"Characters (no spaces)":"Символи (без пробілів)",
"Circle":"Коло",
"Class":"Клас",
"Clear formatting":"Очистити форматування",
"Close":"Закрити",
"Code":"Код",
"Code sample...":"Приклад коду...",
"Code view":"Перегляд коду",
"Color Picker":"Вибір кольору",
"Color swatch":"Зразок кольору",
"Cols":"Стовпці",
"Column":"Стовпець",
"Column clipboard actions":"Дії буфера обміну для стовпця",
"Column group":"Група стовпців",
"Column header":"Заголовок стовпця",
"Constrain proportions":"Обмежити пропорції",
"Copy":"Копіювати",
"Copy column":"Копіювати стовпець",
"Copy row":"Копіювати рядок",
"Could not find the specified string.":"Не вдалося знайти вказаний рядок.",
"Could not load emojis":"Не вдалося завантажити емодзі",
"Count":"Кількість",
"Currency":"Валюта",
"Current window":"Поточне вікно",
"Custom color":"Користувацький колір",
"Custom...":"Користувацький...",
"Cut":"Вирізати",
"Cut column":"Вирізати стовпець",
"Cut row":"Вирізати рядок",
"Dark Blue":"Темно-синій",
"Dark Gray":"Темно-сірий",
"Dark Green":"Темно-зелений",
"Dark Orange":"Темно-помаранчевий",
"Dark Purple":"Темно-фіолетовий",
"Dark Red":"Темно-червоний",
"Dark Turquoise":"Темно-бірюзовий",
"Dark Yellow":"Темно-жовтий",
"Dashed":"Пунктирна",
"Date/time":"Дата/час",
"Decrease indent":"Зменшити відступ",
"Default":"За замовчуванням",
"Delete accordion":"",
"Delete column":"Видалити стовпець",
"Delete row":"Видалити рядок",
"Delete table":"Видалити таблицю",
"Dimensions":"Розміри",
"Disc":"Диск",
"Div":"Div",
"Document":"Документ",
"Dotted":"Крапкова",
"Double":"Подвійна",
"Drop an image here":"Перетягніть зображення сюди",
"Dropped file type is not supported":"Тип файлу не підтримується",
"Edit":"Редагувати",
"Embed":"Вбудований",
"Emojis":"Емодзі",
"Emojis...":"Емодзі...",
"Error":"Помилка",
"Error: Form submit field collision.":"Помилка: Конфлікт полів відправки форми.",
"Error: No form element found.":"Помилка: Елемент форми не знайдено.",
"Extended Latin":"Розширена латиниця",
"Failed to initialize plugin: {0}":"Помилка ініціалізації плагіна: {0}",
"Failed to load plugin url: {0}":"Помилка завантаження URL плагіна: {0}",
"Failed to load plugin: {0} from url {1}":"Помилка завантаження плагіна: {0} з URL {1}",
"Failed to upload image: {0}":"Помилка завантаження зображення: {0}",
"File":"Файл",
"Find":"Знайти",
"Find (if searchreplace plugin activated)":"Знайти (якщо плагін searchreplace активований)",
"Find and Replace":"Знайти та замінити",
"Find and replace...":"Знайти та замінити...",
"Find in selection":"Шукати в виділеному",
"Find whole words only":"Знайти тільки цілі слова",
"Flags":"Прапори",
"Focus to contextual toolbar":"Фокус на контекстну панель інструментів",
"Focus to element path":"Фокус на шлях елемента",
"Focus to menubar":"Фокус на панель меню",
"Focus to toolbar":"Фокус на панель інструментів",
"Font":"Шрифт",
"Font size {0}":"",
"Font sizes":"Розміри шрифту",
"Font {0}":"",
"Fonts":"Шрифти",
"Food and Drink":"Їжа та напої",
"Footer":"Нижній колонтитул",
"Format":"Формат",
"Format {0}":"",
"Formats":"Формати",
"Fullscreen":"Повний екран",
"G":"G",
"General":"Загальні",
"Gray":"Сірий",
"Green":"Зелений",
"Green component":"Зелена компонента",
"Groove":"Жолоб",
"Handy Shortcuts":"Корисні скорочення",
"Header":"Верхній колонтитул",
"Header cell":"Клітинка верхнього колонтитулу",
"Heading 1":"Заголовок 1",
"Heading 2":"Заголовок 2",
"Heading 3":"Заголовок 3",
"Heading 4":"Заголовок 4",
"Heading 5":"Заголовок 5",
"Heading 6":"Заголовок 6",
"Headings":"Заголовки",
"Height":"Висота",
"Help":"Довідка",
"Hex color code":"HEX код кольору",
"Hidden":"Прихований",
"Horizontal align":"Горизонтальне вирівнювання",
"Horizontal line":"Горизонтальна лінія",
"Horizontal space":"Горизонтальний інтервал",
"ID":"ID",
"ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.":"ID повинен починатися з літери, за якою слідують тільки літери, цифри, тире, крапки, двокрапки або підкреслення.",
"Image is decorative":"Зображення є декоративним",
"Image list":"Список зображень",
"Image title":"Назва зображення",
"Image...":"Зображення...",
"ImageProxy HTTP error: Could not find Image Proxy":"HTTP помилка ImageProxy: Не вдалося знайти Image Proxy",
"ImageProxy HTTP error: Incorrect Image Proxy URL":"HTTP помилка ImageProxy: Неправильний URL Image Proxy",
"ImageProxy HTTP error: Rejected request":"HTTP помилка ImageProxy: Відхилений запит",
"ImageProxy HTTP error: Unknown ImageProxy error":"HTTP помилка ImageProxy: Невідома помилка ImageProxy",
"Increase indent":"Збільшити відступ",
"Inline":"Вбудований",
"Insert":"Вставити",
"Insert Template":"Вставити шаблон",
"Insert accordion":"",
"Insert column after":"Вставити стовпець праворуч",
"Insert column before":"Вставити стовпець ліворуч",
"Insert date/time":"Вставити дату/час",
"Insert image":"Вставити зображення",
"Insert link (if link plugin activated)":"Вставити посилання (якщо плагін link активований)",
"Insert row after":"Вставити рядок знизу",
"Insert row before":"Вставити рядок зверху",
"Insert table":"Вставити таблицю",
"Insert template...":"Вставити шаблон...",
"Insert video":"Вставити відео",
"Insert/Edit code sample":"Додати/Редагувати приклад коду",
"Insert/edit image":"Вставити/редагувати зображення",
"Insert/edit link":"Вставити/редагувати посилання",
"Insert/edit media":"Вставити/редагувати медіа",
"Insert/edit video":"Вставити/редагувати відео",
"Inset":"Вставка",
"Invalid hex color code: {0}":"Недійсний HEX код кольору: {0}",
"Invalid input":"Недійсний ввід",
"Italic":"Курсив",
"Justify":"Вирівняти по ширині",
"Keyboard Navigation":"Навігація клавіатурою",
"Language":"Мова",
"Learn more...":"Дізнатися більше...",
"Left":"Ліворуч",
"Left to right":"Зліва направо",
"Light Blue":"Світло-синій",
"Light Gray":"Світло-сірий",
"Light Green":"Світло-зелений",
"Light Purple":"Світло-фіолетовий",
"Light Red":"Світло-червоний",
"Light Yellow":"Світло-жовтий",
"Line height":"Висота рядка",
"Link list":"Список посилань",
"Link...":"Посилання...",
"List Properties":"Властивості списку",
"List properties...":"Властивості списку...",
"Loading emojis...":"Завантаження емодзі...",
"Loading...":"Завантаження...",
"Lower Alpha":"Малі літери",
"Lower Greek":"Малі грецькі",
"Lower Roman":"Малі римські",
"Match case":"Враховувати регістр",
"Mathematical":"Математичні",
"Media poster (Image URL)":"Постер медіа (URL зображення)",
"Media...":"Медіа...",
"Medium Blue":"Середньо-синій",
"Medium Gray":"Середньо-сірий",
"Medium Purple":"Середньо-фіолетовий",
"Merge cells":"Об'єднати клітинки",
"Middle":"Середина",
"Midnight Blue":"Північно-синій",
"More...":"Більше...",
"Name":"Назва",
"Navy Blue":"Темно-синій",
"New document":"Новий документ",
"New window":"Нове вікно",
"Next":"Далі",
"No":"Ні",
"No alignment":"Без вирівнювання",
"No color":"Без кольору",
"Nonbreaking space":"Нерозривний пробіл",
"None":"Жоден",
"Numbered list":"Нумерований список",
"OR":"АБО",
"Objects":"Об'єкти",
"Ok":"OK",
"Open help dialog":"Відкрити діалог довідки",
"Open link":"Відкрити посилання",
"Open link in...":"Відкрити посилання в...",
"Open popup menu for split buttons":"Відкрити спливаюче меню для розділених кнопок",
"Orange":"Помаранчевий",
"Outset":"Виступ",
"Page break":"Розрив сторінки",
"Paragraph":"Абзац",
"Paste":"Вставити",
"Paste as text":"Вставити як текст",
"Paste column after":"Вставити стовпець праворуч",
"Paste column before":"Вставити стовпець ліворуч",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.":"Вставка тепер у режимі звичайного тексту. Вміст буде вставлятися як звичайний текст, поки ви не вимкнете цю опцію.",
"Paste or type a link":"Вставте або введіть посилання",
"Paste row after":"Вставити рядок знизу",
"Paste row before":"Вставити рядок зверху",
"Paste your embed code below:":"Вставте свій вбудований код нижче:",
"People":"Люди",
"Plugins":"Плагіни",
"Plugins installed ({0}):":"Встановлені плагіни ({0}):",
"Powered by {0}":"Працює на {0}",
"Pre":"Pre",
"Preferences":"Налаштування",
"Preformatted":"Попередньо відформатований",
"Premium plugins:":"Преміум плагіни:",
"Press the Up and Down arrow keys to resize the editor.":"",
"Press the arrow keys to resize the editor.":"",
"Press {0} for help":"",
"Preview":"Попередній перегляд",
"Previous":"Попередній",
"Print":"Друк",
"Print...":"Друк...",
"Purple":"Фіолетовий",
"Quotations":"Цитати",
"R":"R",
"Range 0 to 255":"Діапазон від 0 до 255",
"Red":"Червоний",
"Red component":"Червона компонента",
"Redo":"Повторити",
"Remove":"Видалити",
"Remove color":"Видалити колір",
"Remove link":"Видалити посилання",
"Replace":"Замінити",
"Replace all":"Замінити все",
"Replace with":"Замінити на",
"Resize":"Змінити розмір",
"Restore last draft":"Відновити останній чернетку",
"Reveal or hide additional toolbar items":"",
"Rich Text Area":"Область форматування тексту",
"Rich Text Area. Press ALT-0 for help.":"Область форматування тексту. Натисніть ALT-0 для довідки.",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help":"Область форматування тексту. Натисніть ALT-F9 для меню, ALT-F10 для панелі інструментів, ALT-0 для довідки",
"Ridge":"Гребінь",
"Right":"Праворуч",
"Right to left":"Справа наліво",
"Row":"Рядок",
"Row clipboard actions":"Дії буфера обміну для рядка",
"Row group":"Група рядків",
"Row header":"Заголовок рядка",
"Row properties":"Властивості рядка",
"Row type":"Тип рядка",
"Rows":"Рядки",
"Save":"Зберегти",
"Save (if save plugin activated)":"Зберегти (якщо плагін save активований)",
"Scope":"Область",
"Search":"Пошук",
"Select all":"Вибрати все",
"Select...":"Вибрати...",
"Selection":"Вибір",
"Shortcut":"Скорочення",
"Show blocks":"Показати блоки",
"Show caption":"Показати підпис",
"Show invisible characters":"Показати невидимі символи",
"Size":"Розмір",
"Solid":"Суцільна",
"Source":"Джерело",
"Source code":"Вихідний код",
"Special Character":"Спеціальний символ",
"Special character...":"Спеціальний символ...",
"Split cell":"Розділити клітинку",
"Square":"Квадрат",
"Start list at number":"Почати нумерацію з",
"Strikethrough":"Закреслення",
"Style":"Стиль",
"Subscript":"Нижній індекс",
"Superscript":"Верхній індекс",
"Switch to or from fullscreen mode":"Перемкнути в або з повноекранного режиму",
"Symbols":"Символи",
"System Font":"Системний шрифт",
"Table":"Таблиця",
"Table caption":"Підпис таблиці",
"Table properties":"Властивості таблиці",
"Table styles":"Стилі таблиці",
"Template":"Шаблон",
"Templates":"Шаблони",
"Text":"Текст",
"Text color":"Колір тексту",
"Text color {0}":"",
"Text to display":"Текст для відображення",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?":"URL, який ви ввели, схожий на адресу електронної пошти. Чи хочете додати необхідний префікс mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?":"URL, який ви ввели, схожий на зовнішнє посилання. Чи хочете додати необхідний префікс http://?",
"The URL you entered seems to be an external link. Do you want to add the required https:// prefix?":"URL, який ви ввели, схожий на зовнішнє посилання. Чи хочете додати необхідний префікс https://?",
"Title":"Назва",
"To open the popup, press Shift+Enter":"Для відкриття спливаючого меню натисніть Shift+Enter",
"Toggle accordion":"",
"Tools":"Інструменти",
"Top":"Зверху",
"Travel and Places":"Подорожі та місця",
"Turquoise":"Бірюзовий",
"Underline":"Підкреслення",
"Undo":"Скасувати",
"Upload":"Завантажити",
"Uploading image":"Завантаження зображення",
"Upper Alpha":"Великі літери",
"Upper Roman":"Великі римські",
"Url":"URL",
"User Defined":"Визначено користувачем",
"Valid":"Дійсний",
"Version":"Версія",
"Vertical align":"Вертикальне вирівнювання",
"Vertical space":"Вертикальний інтервал",
"View":"Перегляд",
"Visual aids":"Візуальні підказки",
"Warn":"Попередження",
"White":"Білий",
"Width":"Ширина",
"Word count":"Кількість слів",
"Words":"Слова",
"Words: {0}":"Слова: {0}",
"Yellow":"Жовтий",
"Yes":"Так",
"You are using {0}":"Ви використовуєте {0}",
"You have unsaved changes are you sure you want to navigate away?":"У вас є незбережені зміни. Ви впевнені, що хочете перейти?",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":"Ваш браузер не підтримує прямий доступ до буфера обміну. Будь ласка, використовуйте клавіатурні скорочення Ctrl+X/C/V.",
"alignment":"вирівнювання",
"austral sign":"знак австрал",
"cedi sign":"знак седі",
"colon sign":"двокрапка",
"cruzeiro sign":"знак крузейро",
"currency sign":"знак валюти",
"dollar sign":"знак долара",
"dong sign":"знак донг",
"drachma sign":"знак драхми",
"euro-currency sign":"знак євро",
"example":"приклад",
"formatting":"форматування",
"french franc sign":"знак французького франка",
"german penny symbol":"знак німецького пенні",
"guarani sign":"знак гуарані",
"history":"історія",
"hryvnia sign":"знак гривні",
"indentation":"відступ",
"indian rupee sign":"знак індійської рупії",
"kip sign":"знак кіп",
"lira sign":"знак ліри",
"livre tournois sign":"знак livre tournois",
"manat sign":"знак маната",
"mill sign":"знак міл",
"naira sign":"знак найри",
"new sheqel sign":"знак нового шекеля",
"nordic mark sign":"знак нордичної марки",
"peseta sign":"знак песети",
"peso sign":"знак песо",
"ruble sign":"знак рубля",
"rupee sign":"знак рупії",
"spesmilo sign":"знак спесміло",
"styles":"стилі",
"tenge sign":"знак тенге",
"tugrik sign":"знак тугрика",
"turkish lira sign":"знак турецької ліри",
"won sign":"знак вона",
"yen character":"знак єни",
"yen/yuan character variant one":"знак єни/юаня, варіант 1",
"yuan character":"знак юаня",
"yuan character, in hong kong and taiwan":"знак юаня, Гонконг і Тайвань",
"{0} characters":"{0} символів",
"{0} columns, {1} rows":"",
"{0} words":"{0} слів"
});
